chore(root): enforce github user email in precommit
mi6/ic-ui-kit pull request #1037
Opened 2023-08-25 14:29 UTC by GCHQ-Developer-299

Added a email checking script to husky precommit hook that enforces git email to be set to github user email address. Added guidance to contributing.md

## Summary of the changes
Tell us, in a few words, what the changes are.

## Related issue
Tell us the issue number. If suggesting an improvement or component, please discuss it with us in an issue first.

## Checklist
- [ ] I have added relevant unit and visual regression tests.
- [ ] I have manually accessibility tested any changes, if relevant.
- [ ] I have ensured any changes match the Figma component library.

2023-08-29 07:36 UTC, GCHQ-Developer-530 approved these changes

2023-08-29 14:36 UTC, MI6-255 requested changes
Two very small docs changes (pedantic ones I apologise). Happy with the code. This change will also need applying to ic-design-system

2023-08-29 14:36 UTC, MI6-255 commented on CONTRIBUTING.md
> +1. Visit your [Github email settings](https://github.com/settings/emails)
Pedantic, I apologise 
```suggestion
1. Visit your [GitHub email settings](https://github.com/settings/emails)

```

2023-08-29 14:36 UTC, MI6-255 commented on CONTRIBUTING.md
> +As a data protection measure, this repository enforces the use of Github user email address in your commit. Please follow these steps:
```suggestion
As a data protection measure, this repository enforces the use of GitHub user email address in your commit. Please follow these steps:

```

2023-08-30 06:32 UTC, GCHQ-Developer-530 approved these changes

2023-08-30 07:40 UTC, merged