fix(web-components): add margin top and bottom to icon button
mi6/ic-ui-kit pull request #1112
Opened 2023-09-21 14:08 UTC by GCHQ-Developer-530

## Summary of the changes
Add margin top and bottom to icon button so that nothing nearby appears within the button

## Related issue
#891

## Checklist
- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] All acceptance criteria reviewed and met. 
- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] Browser support tested (Chrome, Safari, Firefox and Edge).
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [x] All prop combinations work without issue.

2023-09-22 10:01 UTC, MI6-255 approved these changes

2023-09-29 10:54 UTC, GCHQ-Developer-465 approved these changes

2023-09-29 12:45 UTC, ad9242 requested changes
There still sems to be the original issue where a slight outline in each corner when the button is focused
![image](https://github.com/mi6/ic-ui-kit/assets/116102637/6b938eb5-c208-40da-b80d-08fdcebf021c)
![image](https://github.com/mi6/ic-ui-kit/assets/116102637/bdd0885b-b63a-492c-8dad-96e13319448e)

2023-10-03 07:30 UTC, GCHQ-Developer-530 commented
> There still sems to be the original issue where a slight outline in each corner when the button is focused ![image](https://user-images.githubusercontent.com/116102637/271580597-6b938eb5-c208-40da-b80d-08fdcebf021c.png) ![image](https://user-images.githubusercontent.com/116102637/271581937-bdd0885b-b63a-492c-8dad-96e13319448e.png)

I think there will always be this issue, it occurs because it thinks there's a colour difference between white and transparent on a white background. But changing the background colour of the button to white isn't really an option as it's needed on pagination and other things as transparent.

2023-10-03 12:31 UTC, GCHQ-Developer-847 approved these changes

2023-10-03 13:46 UTC, ad9242 approved these changes

2023-10-03 14:29 UTC, merged