860 ic top navigation double reading
mi6/ic-ui-kit pull request #1127
Opened 2023-09-27 14:42 UTC by GCHQ-Developer-299

## Summary of the changes
Added a silent prop to the ic-tooltip, for instances where the tooltip is duplicating the visible text of the child component. 

Set the tooltips for icon-variant buttons and navigation-items to be silent, as they already have accessible names. 

I've tested this thoroughly with Voiceover (both by tabbing through and moving the virtual cursor) on icon buttons, side/top navigation and ic-tooltip. I've also added a new "silent" story to the ic-tooltip. 

I am unsure how this gels with the [mozilla guidance on role=tooltip](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role) since this change ignores it. Functionally this does solve the double-reading bug and preserves functionality of the tooltip though.

## Related issue
#860

## Checklist
- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] All acceptance criteria reviewed and met. 
- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge).
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [ ] All prop combinations work without issue.

2023-10-02 13:17 UTC, jd239 requested changes
Wondering if another way to look at this ticket is to figure out whether aria-hidden on the tooltip should be set to true or false or would that prevent any of it's children such as button from being read out?

2023-10-02 13:17 UTC, jd239 commented on packages/web-components/src/components/ic-tooltip/ic-tooltip.stories.mdx
> +      html`<ic-tooltip
Hovering over this button produces two tooltips. One generated from the browser and the other, an `ic-tooltip`

2023-10-02 13:17 UTC, jd239 commented on packages/web-components/src/components/ic-tooltip/ic-tooltip.tsx
> +      <Host class={{ "ic-tooltip": true }} title={!this.silent ? label : null}>
Title will produce the browser tooltip as well as the `ic-tooltip`

2023-10-17 09:47 UTC, GCHQ-Developer-299 commented
PR has become stale and there's significant feedback to address. Will close and return with another branch.

2023-10-17 09:47 UTC, closed without merging