Remove slot name in ic nav item
mi6/ic-ui-kit pull request #1130
Opened 2023-09-28 16:12 UTC by j212122

## Summary of the changes

- Added unnamed slot rendering
- Updated ic-navigation-item/ ic-navigation-group styling
- Fixed app-title slot bug
- Added additional React stories for testing
- Updated ic-nav label styling
- Added visual regression tests
- Added unit and e2e tests
- Updated side-nav animations

## Related issue
#1071 
#845 

## Checklist
- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] All acceptance criteria reviewed and met. 
- [x] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Min/max content examples tested with no loss of content or overflow. 
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge).
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [x] All prop combinations work without issue.

2023-09-29 10:45 UTC, GCHQ-Developer-465 reviewed
Overall, very impressive! Only some small comments :)

2023-09-29 10:45 UTC, GCHQ-Developer-465 commented on packages/web-components/src/components/ic-top-navigation/test/basic/ic-top-navigation.mobile.e2e.ts
> +        href="#"
Is this line supposed to be here? If so, for my understanding what is the purpose of having a href="#"?

2023-09-29 10:45 UTC, GCHQ-Developer-465 commented on packages/web-components/src/components/ic-side-navigation/test/basic/ic-side-navigation.e2e.ts
> +    it("renders visible labels when slotted menu items and expanded", async () => {
```suggestion
    it("renders visible labels when slotted menu items and side nav is expanded", async () => {
```
For consistency thought to add this :)

2023-10-02 14:10 UTC, ad9242 commented
In the React  "react router" and "react router with unnamed slot" stories, there's a bit of an alignment issue with the icon\title:

![image](https://github.com/mi6/ic-ui-kit/assets/116102637/05c69362-c097-49b6-860e-5e616255b684)

Is it just an issue with our examples or more of a component issue?

2023-10-02 14:55 UTC, ad9242 requested changes

2023-10-02 14:55 UTC, ad9242 commented on packages/web-components/src/components/ic-navigation-group/ic-navigation-group.tsx
> +        }, 125);
Could DYNAMIC_GROUPED_LINKS_HEIGHT_MS be used instead (100ms vs 125ms)?? If not can we add new variable & also use on line 176?

2023-10-02 14:55 UTC, ad9242 commented on packages/web-components/src/components/ic-side-navigation/ic-side-navigation.css
>    --navigation-item-height: 3.5rem;
```suggestion
```
remove this? as definition duplicated on line 328

2023-10-02 14:55 UTC, ad9242 commented on packages/web-components/src/components/ic-navigation-item/ic-navigation-item.css
> +  padding-top: var(--ic-space-md) !important;
replace with single padding: to fix lint error

2023-10-02 14:57 UTC, ad9242 commented
also ran a `npm run lint:fix` to resolve a couple of other errors

2023-10-03 15:13 UTC, ad9242 approved these changes

2023-10-04 10:06 UTC, GCHQ-Developer-741 submitted a review, later dismissed

2023-10-06 08:17 UTC, ad9242 submitted a review, later dismissed

2023-10-06 08:54 UTC, GCHQ-Developer-465 submitted a review, later dismissed

2023-10-06 13:23 UTC, ad9242 approved these changes

2023-10-06 13:29 UTC, GCHQ-Developer-741 approved these changes

2023-10-06 13:31 UTC, GCHQ-Developer-465 approved these changes

2023-10-10 07:47 UTC, merged