Remove unused storybook pages #1141
mi6/ic-ui-kit pull request #1165
Opened 2023-10-10 13:01 UTC by GCHQ-Developer-398

## Summary of the changes
Removal of unused storybook pages. Getting started from react folder. Getting started, theme and usage pages from web-components folder.

## Related issue
Issue #1141 

## Checklist
- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] All acceptance criteria reviewed and met. 
- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] Browser support tested (Chrome, Safari, Firefox and Edge).
- [x] Correct roles used and ARIA attributes used correctly were required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [x] All prop combinations work without issue.

2023-10-10 13:07 UTC, GCHQ-Developer-741 approved these changes

2023-10-11 08:41 UTC, GCHQ-Developer-741 submitted a review, later dismissed

2023-10-11 08:47 UTC, GCHQ-Developer-299 approved these changes

2023-10-11 08:50 UTC, GCHQ-Developer-398 commented
Do not merge until rebase is complete, and any conflicts that arise are resolved.

2023-10-11 08:51 UTC, GCHQ-Developer-530 requested changes
Just waiting on main -> develop

2023-10-11 08:57 UTC, GCHQ-Developer-530 approved these changes

2023-10-11 09:01 UTC, GCHQ-Developer-741 approved these changes

2023-10-11 09:15 UTC, merged