feat(web-components): adds form and related props to select, radio an…
mi6/ic-ui-kit pull request #1177
Opened 2023-10-16 12:32 UTC by j212122

## Summary of the changes
adds form and related props to select, radio and checkbox. Adds relevant tests
Updates vulnerability list to prevent build failing

## Related issue
#1013 

## Checklist
- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] All acceptance criteria reviewed and met. 
- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] Browser support tested (Chrome, Safari, Firefox and Edge).
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [x] All prop combinations work without issue.

2023-10-16 13:43 UTC, GCHQ-Developer-530 requested changes

2023-10-16 13:43 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-checkbox-group/test/basic/ic-checkbox-group.spec.ts
> +  it("should test radio option as submit on form", async () => {
```suggestion
  it("should test checkbox as submit on form", async () => {
```

2023-10-16 13:43 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-select/ic-select.tsx
> +   * The <form> element to associate the select with. Use only this prop on searchable select.
I think it's the other way around with the searchable select comment. Should be on all form props except form itself. Might also want rewording to something like "this prop will only be applied if searchable is true"

2023-10-17 13:26 UTC, GCHQ-Developer-299 approved these changes

2023-10-17 14:01 UTC, GCHQ-Developer-530 approved these changes

2023-10-17 14:03 UTC, merged