^t
mi6/ic-ui-kit pull request #1218
Opened 2023-10-24 13:31 UTC by j212122

## Summary of the changes
adds pressed button styling whilst ensuring the order of events is: 

Button exists on page unfocused or hovered showing default state.
Mouse over causes hover state.
Mouse down causes active state plus applies focus
Mouse up event causes complete click event (if still over button) and button remains hovered and focused.
Mouse leaves button area causing default state to return, with focus still displayed.

## Related issue
#844 

## Checklist
- [x] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] All acceptance criteria reviewed and met. 
- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge).
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [ ] All prop combinations work without issue.

2023-10-24 14:46 UTC, ad9242 commented
The text on primary button (light) hover changes colour depending on whether it has focus or not. Is that correct?

![image](https://github.com/mi6/ic-ui-kit/assets/116102637/18119c00-8701-4164-93d1-de2c34b077b2)

2023-10-24 15:01 UTC, GCHQ-Developer-299 submitted a review, later dismissed

2023-10-24 17:03 UTC, DBD324 commented
> The text on primary button (light) hover changes colour depending on whether it has focus or not. Is that correct?
> 
> ![image](https://user-images.githubusercontent.com/116102637/277701436-18119c00-8701-4164-93d1-de2c34b077b2.png)

This is indeed an issue, the designs in Figma show how the dark variant button should be styled. The text colour should remain the same for the pressed state.

2023-10-24 17:22 UTC, DBD324 requested changes
Looks good, there's just the problem with the light appearance primary button changing text colour on pressed state.

2023-10-25 07:55 UTC, GCHQ-Developer-299 submitted a review, later dismissed

2023-10-25 08:10 UTC, ad9242 submitted a review, later dismissed

2023-11-02 09:03 UTC, DBD324 approved these changes

2023-11-02 10:23 UTC, GCHQ-Developer-299 approved these changes

2023-11-03 09:11 UTC, DBD324 approved these changes

2023-11-03 09:23 UTC, ad9242 approved these changes

2023-11-03 09:33 UTC, merged