1273 ic select allow icoptionselect event to be fired on enter instead of arrowdown
mi6/ic-ui-kit pull request #1297
Opened 2023-12-04 09:44 UTC by GCHQ-Developer-530

## Summary of the changes
Add selectOnEnter prop to select component to determine when icOptionSelect is emitted (either on enter or arrow down)

## Related issue
#1273 

## Checklist
- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] All acceptance criteria reviewed and met. 
- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] Browser support tested (Chrome, Safari, Firefox and Edge).
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [x] All prop combinations work without issue. 
- [x] Changes to docs package checked and committed.

2023-12-04 10:46 UTC, GCHQ-Developer-299 commented
I'm not sure this fulfils the requirement - while it does only emit the event on enter, the value that appears selected in the select field still changes when you arrow through the menu. 
This leads to unusual behaviour where if you arrow through to an option, then press Esc to close the menu, then open the menu again using spacebar, the event fires on the item that was in the field (even though the user never actually pressed enter on that item)

2023-12-04 14:33 UTC, GCHQ-Developer-299 submitted a review, later dismissed

2023-12-05 08:56 UTC, ad9242 commented
found an issue with the async select default story if you set the new prop. if you make a selection, say "espresso", then use arrow down key, you can't see the current focused item/items above the selected at the top of the list. 

eg below the current focused item is not visible:
![image](https://github.com/mi6/ic-ui-kit/assets/116102637/41f643af-a1be-485d-9a07-23e57d22b3a3)

seems to be it doesn't scroll the item into view in this mode

2023-12-05 10:25 UTC, GCHQ-Developer-299 approved these changes

2023-12-05 11:20 UTC, ad9242 requested changes
can we add a test to make sure the event is only emitted when enter is pressed?

2023-12-05 11:57 UTC, ad9242 approved these changes

2023-12-05 11:58 UTC, GCHQ-Developer-299 approved these changes

2023-12-05 11:59 UTC, merged