feat: add top prop to ic-classification-banner
mi6/ic-ui-kit pull request #1336
Opened 2023-12-20 14:47 UTC by MI6-682

## Summary of the changes
Added "top" prop to classification banner. Also adds relevant changes to top nav and side nav to deal with this change.

## Related issue
#1317 

## Checklist
- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] All acceptance criteria reviewed and met. 
- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge).
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [ ] All prop combinations work without issue. 
- [ ] Changes to docs package checked and committed.

2023-12-20 14:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1336) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1336) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=1336) it.</sub>

2023-12-20 15:51 UTC, MI6-682 commented
I force updated the commit to fix a prettier issue but I can't figure out how to re-run the checks 🤔

2023-12-21 16:41 UTC, MI6-682 commented
Just fixed an issue with using both top and bottom banners with side nav and also op nav when zoomed

2023-12-22 13:24 UTC, ad9242 commented
on smaller device sizes, The top of the popout menu is obscured by the top banner - modified the "Theming" top-navigation story to see this

![image](https://github.com/mi6/ic-ui-kit/assets/116102637/710b7185-5693-4217-b260-d47de3921862)

2023-12-22 14:10 UTC, jd239 requested changes
Thanks for the contribution. I've added two minor comments.

2023-12-22 14:10 UTC, jd239 commented on packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx
On  L523, there is a check on the viewport/device size and a padding-top is applied so the mobile top bar does not overlap the content. This will have to be updated to take into consideration the classification banner.

2024-01-03 11:28 UTC, jd239 commented
Hi @MI6-682. Looks like there is a conflict with the docs.json file. When possible, can you please resolve the conflicts so the PR can be re-reviewed. Thanks.

2024-01-04 08:16 UTC, GCHQ-Developer-530 commented on packages/web-components/src/utils/helpers.ts
> +  }
I'm not sure this if statement is needed as you've never passed through a "notInline" type, and the `:not([inline='true'])` is covered by the type bottom if statement

2024-01-17 10:35 UTC, MI6-255 commented
@MI6-27 will follow up with you today

2024-01-17 10:35 UTC, closed without merging