1321 add dropdown button variant
mi6/ic-ui-kit pull request #1396
Opened 2024-01-17 13:42 UTC by GCHQ-Developer-530

## Summary of the changes
Add dropdown option to button, add cypress tests. Also add icPopoverClosed event to help users using the dropdown with popover menu. 

## Related issue
#1321 

## Checklist
- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] All acceptance criteria reviewed and met. 
- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] Browser support tested (Chrome, Safari, Firefox and Edge).
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [x] All prop combinations work without issue. 
- [x] Changes to docs package checked and committed.

2024-01-17 15:08 UTC, GCHQ-Developer-530 commented
> There seems to be extra padding on the right... does this match the designs? Worth having @DBD324 looking into this also. <img alt="Screenshot 2024-01-17 at 15 00 13" width="285" src="https://private-user-images.githubusercontent.com/111882114/297421880-4da46b4f-b46a-43d3-bcc5-f6a8503a303d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDQyNDMsIm5iZiI6MTcwNTUwMzk0MywicGF0aCI6Ii8xMTE4ODIxMTQvMjk3NDIxODgwLTRkYTQ2YjRmLWI0NmEtNDNkMy1iY2M1LWY2YTg1MDNhMzAzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxNTA1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2VjOTY3ZTA1N2YzMTI1MGI0OTYyMDU2MjQ1OGY3ZGFhNGRlZTBkYjE0Y2JiZjkyMDgwZDMzYmY5ZjRkMzgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lS42IOHH6DQyfIDF1T4J4_E8mRaMViFrQwlDPC-iURc">

I noticed that as well. It does seem to match the designs though. @DBD324 did mention this yesterday saying that they were worried that if there was no left icon it might look too big but they left it as is. 
<img width="272" alt="Screenshot 2024-01-17 at 15 06 27" src="https://github.com/mi6/ic-ui-kit/assets/111882034/d791a082-a2ea-491e-8439-26bed25ca5eb">

2024-01-17 15:52 UTC, GCHQ-Developer-299 commented on packages/web-components/src/components/ic-button/ic-button.tsx
> +   * If `true`, the button will be blah.
Will the button be blah?  I reckon this comment should say something else ;)

2024-01-17 15:53 UTC, GCHQ-Developer-299 commented on packages/react/cypress-visual-screenshots/baseline/IcButton.cy.tsx-dropdown.png
For a cypress screenshot i'd like to see maybe the dropdown example (like you've got in Storybook) open, so we can see the arrow having switched and the additional content being displayed.

2024-01-17 16:54 UTC, GCHQ-Developer-465 commented
> > There seems to be extra padding on the right... does this match the designs? Worth having @DBD324 looking into this also. <img alt="Screenshot 2024-01-17 at 15 00 13" width="285" src="https://private-user-images.githubusercontent.com/111882114/297421880-4da46b4f-b46a-43d3-bcc5-f6a8503a303d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDQyNDMsIm5iZiI6MTcwNTUwMzk0MywicGF0aCI6Ii8xMTE4ODIxMTQvMjk3NDIxODgwLTRkYTQ2YjRmLWI0NmEtNDNkMy1iY2M1LWY2YTg1MDNhMzAzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxNTA1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2VjOTY3ZTA1N2YzMTI1MGI0OTYyMDU2MjQ1OGY3ZGFhNGRlZTBkYjE0Y2JiZjkyMDgwZDMzYmY5ZjRkMzgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lS42IOHH6DQyfIDF1T4J4_E8mRaMViFrQwlDPC-iURc">
> 
> I noticed that as well. It does seem to match the designs though. @DBD324 mentioned this yesterday while having a look at it, saying that they were worried that if there was no left icon it might look too big but they left it as is.
> 
> <img alt="Screenshot 2024-01-17 at 15 06 27" width="272" src="https://private-user-images.githubusercontent.com/111882034/297423504-d791a082-a2ea-491e-8439-26bed25ca5eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTAyNTMsIm5iZiI6MTcwNTUwOTk1MywicGF0aCI6Ii8xMTE4ODIwMzQvMjk3NDIzNTA0LWQ3OTFhMDgyLWEyZWEtNDkxZS04NDM5LTI2YmVkMjVjYTVlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxNjQ1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTFhOWYwZTUzNjQwMzY3YmExMDUwYjk0MTA5YjMyZTA5MjQ0MDg5MTU1ZWZkYjMxZjdiN2QwYmUzYmQ3YjczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gB9tJYrVmgdeeK3RzTpeZnLOnsQMYShhBwuUSTrYi1M">

Nice! I still believe that the padding looks off. After some research and looking at others already available online they do not have this extra padding. For instance: 

- [Flowbite](https://www.flowbite-react.com/docs/components/dropdown#default-dropdown)
- [Core UI](https://coreui.io/react/docs/components/dropdown/)
- [React](https://react-bootstrap.netlify.app/docs/components/dropdowns/)

and so on...

This would be a question to @DBD324... has this been taken in consideration. Have you looked at the other sources out there? Why is there extra space and padding? Is this necessary as it looks out of place and should be symmetrical to the left side?

2024-01-19 15:54 UTC, DBD324 commented
> > > There seems to be extra padding on the right... does this match the designs? Worth having @DBD324 looking into this also. <img alt="Screenshot 2024-01-17 at 15 00 13" width="285" src="https://private-user-images.githubusercontent.com/111882114/297421880-4da46b4f-b46a-43d3-bcc5-f6a8503a303d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDQyNDMsIm5iZiI6MTcwNTUwMzk0MywicGF0aCI6Ii8xMTE4ODIxMTQvMjk3NDIxODgwLTRkYTQ2YjRmLWI0NmEtNDNkMy1iY2M1LWY2YTg1MDNhMzAzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxNTA1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2VjOTY3ZTA1N2YzMTI1MGI0OTYyMDU2MjQ1OGY3ZGFhNGRlZTBkYjE0Y2JiZjkyMDgwZDMzYmY5ZjRkMzgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lS42IOHH6DQyfIDF1T4J4_E8mRaMViFrQwlDPC-iURc">
> > 
> > 
> > I noticed that as well. It does seem to match the designs though. @DBD324 mentioned this yesterday while having a look at it, saying that they were worried that if there was no left icon it might look too big but they left it as is.
> > <img alt="Screenshot 2024-01-17 at 15 06 27" width="272" src="https://private-user-images.githubusercontent.com/111882034/297423504-d791a082-a2ea-491e-8439-26bed25ca5eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTAyNTMsIm5iZiI6MTcwNTUwOTk1MywicGF0aCI6Ii8xMTE4ODIwMzQvMjk3NDIzNTA0LWQ3OTFhMDgyLWEyZWEtNDkxZS04NDM5LTI2YmVkMjVjYTVlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxNjQ1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTFhOWYwZTUzNjQwMzY3YmExMDUwYjk0MTA5YjMyZTA5MjQ0MDg5MTU1ZWZkYjMxZjdiN2QwYmUzYmQ3YjczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gB9tJYrVmgdeeK3RzTpeZnLOnsQMYShhBwuUSTrYi1M">
> 
> Nice! I still believe that the padding looks off. After some research and looking at others already available online they do not have this extra padding. For instance:
> 
> * [Flowbite](https://www.flowbite-react.com/docs/components/dropdown#default-dropdown)
> * [Core UI](https://coreui.io/react/docs/components/dropdown/)
> * [React](https://react-bootstrap.netlify.app/docs/components/dropdowns/)
> 
> and so on...
> 
> This would be a question to @DBD324... has this been taken in consideration. Have you looked at the other sources out there? Why is there extra space and padding? Is this necessary as it looks out of place and should be symmetrical to the left side?

Apologies for delayed response. Originally this padding was intentional to simplify the button development and keen it consistent. The right hand padding doesn't look too imbalanced when you use a decorative icon on the button at the same time.

However, I have played around with it and tested a few different icon options and I agree we should reduce the right padding to 8px from 16px to account for the visual alignment issue caused by the small glyph within the dropdown icon. The left padding should remain at 16px though.

2024-01-19 16:01 UTC, DBD324 requested changes
The vertical positioning of the dropdown and drop-up icon looks a little off when compared with the Figma designs. It looks too low by a few pixels. Please could you check. 

Also, see comments about right side padding. Agree that we can reduce this to 8px to account for the visual alignment issue.

2024-01-22 09:04 UTC, GCHQ-Developer-299 approved these changes

2024-01-22 10:01 UTC, GCHQ-Developer-465 approved these changes
Much better! 👍  Happy if @DBD324 is happy.

2024-01-22 11:34 UTC, GCHQ-Developer-112 commented on packages/web-components/src/components/ic-button/ic-button.tsx
> +   * If `true`, the button will be in an expanded state.
```suggestion
   * If `true`, the aria-expanded value will be set as true.
```

2024-01-22 12:04 UTC, GCHQ-Developer-299 approved these changes

2024-01-22 12:06 UTC, GCHQ-Developer-112 approved these changes

2024-01-23 09:09 UTC, DBD324 approved these changes
Changes look great. The padding and icon placement look much better now. Thanks

2024-01-23 09:17 UTC, merged