1399 migrate back to top testing over to cypress
mi6/ic-ui-kit pull request #1411
Opened 2024-01-19 15:28 UTC by gd2910

## Summary of the changes
Tell us, in a few words, what the changes are.

## Related issue
Tell us the issue number. If suggesting an improvement or component, please discuss it with us in an issue first.

## Checklist
- [x] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [x] All acceptance criteria reviewed and met. 
- [ ] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge).
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [ ] All prop combinations work without issue. 
- [ ] Changes to docs package checked and committed.

2024-01-22 07:49 UTC, ad9242 requested changes
could we add a test\screenshot where the back-to-top has focus, just to capture that?

2024-01-22 12:29 UTC, GCHQ-Developer-299 commented on packages/react/src/component-tests/IcBackToTop/IcBackToTop.cy.tsx
> +  it("should be hidden", () => {
This is a bit pedantic, but I think this test should have a more specific description. "should be hidden when viewport is at the top of the page"

2024-01-22 12:30 UTC, GCHQ-Developer-530 reviewed
<img width="592" alt="Screenshot 2024-01-22 at 12 28 49" src="https://github.com/mi6/ic-ui-kit/assets/111882034/218ae5cb-8679-4b43-8320-fdc01d4ef072">
The baseline screenshot taken seems to have a ghost back to top further up. Not sure why this might be happening, but could be worth adding a wait before compareSnapshot to see if that gets rid of it?

2024-01-22 12:34 UTC, GCHQ-Developer-299 commented on packages/react/src/component-tests/IcBackToTop/IcBackToTop.cy.tsx
> +  it("should render and pass a11y tests", () => {
You could remove this test and add the checkA11y line into the first 'should appear' test.
The IcSelect tests are good examples of integrating Visual Regression and A11y checks into existing tests

2024-01-23 10:47 UTC, GCHQ-Developer-299 approved these changes

2024-01-23 12:10 UTC, ad9242 approved these changes

2024-01-24 11:39 UTC, merged