264 toggle button
mi6/ic-ui-kit pull request #1424
Opened 2024-01-23 15:10 UTC by GCHQ-Developer-530

## Summary of the changes
Add toggle button component. Update button to have icon top slot.

## Related issue
#264 

## Checklist
- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] All acceptance criteria reviewed and met. 
- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] Browser support tested (Chrome, Safari, Firefox and Edge).
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [x] All prop combinations work without issue. 
- [x] Changes to docs package checked and committed.

2024-01-30 10:53 UTC, GCHQ-Developer-299 commented
I've pushed a change to add Disabled + Checked toggle buttons
![Screenshot 2024-01-30 at 09 45 05](https://github.com/mi6/ic-ui-kit/assets/111292477/0d71aba6-aa31-4915-82dc-11565efe5aa8)

2024-02-01 19:02 UTC, GCHQ-Developer-847 requested changes
A few comments from me, but looking really good! :)

2024-02-02 11:50 UTC, GCHQ-Developer-299 commented on packages/web-components/src/components/ic-toggle-button/ic-toggle-button.tsx
Good spot! I've fixed it in a separate commit - I figure it's not a need for more design, since all other variants of button have :hover:focus stylings, this must have just been missed when devving first time around. 

The fix to IcButton does inherit into ToggleButton too :)

2024-02-05 09:59 UTC, gd2910 commented
Looks great! Just A couple of Cypress comments from me;
- Might be worth capturing a user toggling the button on and off, I see there are tests to check when it can't be clicked, and spec tests to check the toggled prop but I think an e2e also would be good.
- The checkA11y() function can be replaced with checkA11yWithWait() to help against future CI build fails

2024-02-05 10:27 UTC, GCHQ-Developer-299 commented on packages/web-components/src/components/ic-toggle-button/ic-toggle-button.stories.mdx
> +### Icon top
This was being caused by the icon-container having a margin-right by default - have added a class to remove for top icon :)

2024-02-05 10:28 UTC, GCHQ-Developer-299 commented on packages/web-components/src/components/ic-toggle-button/ic-toggle-button.stories.mdx
Have added those stories - it's exposed an incorrect dark variant on loading toggle, darn!

2024-02-05 16:38 UTC, GCHQ-Developer-847 requested changes

2024-02-05 16:38 UTC, GCHQ-Developer-847 commented on packages/web-components/src/components/ic-toggle-button/ic-toggle-button.tsx
Definitely better after your :focus changes :)

However, I'm still seeing a few differences to how they look in the designs (some of which I should have noticed from when I reviewed the PR before - really sorry!):
- The border of the "icon only" toggle button, default appearance, does not go darker on hover and when active.
- The border of the light appearance toggle buttons does not go darker on hover and when active (similar thing with the dark appearance ones - they should go lighter).
- The border of both light and dark appearance toggle buttons when loading should be the active state colours.
- On checked toggle buttons with a light appearance, the gap between the filled-in white rectangle and the border is black whereas I believe it should be transparent. 

Also the "icon only" loading states show the linear loading indicator when they should use the circular variant.

All the colours / state of the default appearance toggle buttons with text, or text with icon, look correct to me though. Don't know if this is helpful, but looking at the designs, when a toggle button is checked, the border colour always matches the colour of the filled-in rectangle (the bit indicating that it's checked).

2024-02-05 16:38 UTC, GCHQ-Developer-847 commented on packages/web-components/src/components/ic-toggle-button/ic-toggle-button.tsx
I feel a bit bad because a few of these issues are inherited from ic-button which should probably have been noticed before! So may feel a bit out of scope but perhaps this is a good time to sort them to prevent too much re-work in future?

Happy if you want to create tickets so that some of the problems can be sorted out at a later time though

2024-02-05 17:26 UTC, GCHQ-Developer-847 commented on packages/web-components/src/components/ic-toggle-button/ic-toggle-button.tsx
> +          aria-checked={`${this.toggleChecked}`}
Yep, looks like a good workaround to me 👍 Tried playing around with it when running locally and also had the same problem. VO repeats the "ticked" / "unticked" this way when you check it but I'd say that's better than it not saying anything!

2024-02-06 18:30 UTC, GCHQ-Developer-847 approved these changes

2024-02-07 07:11 UTC, gd2910 approved these changes

2024-02-07 08:59 UTC, merged