Data entity cypress
mi6/ic-ui-kit pull request #1467
Opened 2024-02-05 10:52 UTC by mmb675

## Summary of the changes
Tell us, in a few words, what the changes are.

## Related issue
Tell us the issue number. If suggesting an improvement or component, please discuss it with us in an issue first.

## Checklist
- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] All acceptance criteria reviewed and met. 
- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge).
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [ ] All prop combinations work without issue. 
- [ ] Changes to docs package checked and committed.

2024-02-05 10:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1467) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1467) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=1467) it.</sub>

2024-02-06 10:27 UTC, GCHQ-Developer-530 requested changes
Just some comments from me - alongside this, there seems to be some formatting issues (the last few tests are particularly difficult to read, so should just need to run prettier).
You'll also need to add loki skip to the visual tests in storybook so they're not looking for any reference images.

2024-02-06 10:27 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcDataEntity/IcDataEntity.cy.tsx
> +  it("milk data e2e and visual testing", () => {
I think if you're testing one data row on its own, we maybe only need one test for it as there's a lot of fairly similar visual tests

2024-02-06 10:27 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcDataEntity/IcDataEntity.cy.tsx
> +  it("milk data e2e and visual testing", () => {
I think the it statements should be more descriptive as well e.g.
```suggestion
  it("should display with only one data row", () => {
```

2024-02-06 10:27 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcDataEntity/IcDataEntity.cy.tsx
> +  it("milk data e2e and visual testing", () => {
This applies to all of the if statements, not just the milk one

2024-02-06 10:35 UTC, GCHQ-Developer-530 commented
I think the threshold needs updating as well because they're failing the cypress tests in the CI build.

2024-02-07 12:11 UTC, GCHQ-Developer-299 submitted a review, later dismissed

2024-02-07 12:19 UTC, GCHQ-Developer-530 submitted a review, later dismissed

2024-02-07 12:32 UTC, GCHQ-Developer-299 approved these changes

2024-02-07 12:39 UTC, GCHQ-Developer-530 approved these changes

2024-02-07 12:39 UTC, merged