feat(ic-dialog): 1429 Add disableWidthConstraint prop to ic-dialog
mi6/ic-ui-kit pull request #1514
Opened 2024-02-14 13:46 UTC by lt94665

## Summary of the changes
Adds the disableWidthConstraint prop to ic-dialogs to optionally override the 75% width restriction on large ic-dialogs

## Related issue
#1429 

## Checklist
- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] All acceptance criteria reviewed and met. 
- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] Browser support tested (Chrome, Safari, Firefox and Edge).
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [x] All prop combinations work without issue. 
- [x] Changes to docs package checked and committed.
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.

2024-02-14 13:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1514) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1514) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=1514) it.</sub>

2024-02-15 11:05 UTC, GCHQ-Developer-530 commented
Hi @lt94665, thanks for the contribution. All of the code looks alright to me, but it looks like it's failing the CI checks for prettier. Please could you run `npm run prettier:fix` and push up the changes made to the dialog files. Thank you 😊

2024-02-15 14:11 UTC, lt94665 commented
@GCHQ-Developer-530 should be good to go now, thanks!

2024-02-16 10:44 UTC, GCHQ-Developer-530 commented
Ran locally and tested and it looks good. Just need a couple of fixes to the commits and then I'll be happy to approve from a developer perspective. Please could you:

- Squash your commits to remove the merge commits
- Update your main web components commit to have web components scope e.g. `feat(web-components): Add disableWidthConstraint prop to ic-dialog`
- Run `npm run build` which should show a change to a docs.json file. Please could you commit this under the docs scope e.g. `docs(docs): Update the docs.json with new dialog prop`.

@DBD324 I've attached a screenshot of the dialog without the 75% content area to demonstrate the behaviour as there is no build for this PR. Please could you take a look from a design perspective?
<img width="857" alt="Screenshot 2024-02-16 at 10 35 28" src="https://github.com/mi6/ic-ui-kit/assets/111882034/79859ae5-0db5-4b28-baf9-2d114d111900">

2024-02-16 15:27 UTC, GCHQ-Developer-299 commented
Heya @lt94665 - thanks for squashing your commits, could you do a rebase off develop to fix the docs.json conflict and then this will be good for us to review :)

2024-02-19 07:52 UTC, GCHQ-Developer-530 submitted a review, later dismissed

2024-02-19 10:09 UTC, GCHQ-Developer-299 requested changes

2024-02-19 10:09 UTC, GCHQ-Developer-299 commented on packages/web-components/src/components/ic-dialog/ic-dialog.css
> +  :host([size="large"]) .dialog:not(.disable-width-constraint) > .content-area {
When i've tried this locally i've found that dialog widths were still restricted by the 'max-width' rule in the .large class (line 78).
![Screenshot 2024-02-19 at 10 09 00](https://github.com/mi6/ic-ui-kit/assets/111292477/80dc20ba-69ba-4246-bf2a-0af7643b9be2)

2024-02-21 13:20 UTC, GCHQ-Developer-530 commented
Hi @lt94665, sorry following the latest release this branch will need rebasing off develop again to resolve the merge conflicts. Please could you do this when you have the time. Thank you

2024-02-21 13:57 UTC, lt94665 commented
@GCHQ-Developer-299 This is meant to change the width of the content area of the dialog, not the width of the actual dialog

![image](https://github.com/mi6/ic-ui-kit/assets/155549177/cba81bbd-f682-4610-8da6-c48cc71f4049)

Happy to update the documentation/prop name if you don't think that's clear enough?

2024-02-21 15:15 UTC, GCHQ-Developer-299 commented
> @GCHQ-Developer-299 This is meant to change the width of the content area of the dialog, not the width of the actual dialog
> 
> ![image](https://private-user-images.githubusercontent.com/155549177/306647444-cba81bbd-f682-4610-8da6-c48cc71f4049.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1Mjg3NzIsIm5iZiI6MTcwODUyODQ3MiwicGF0aCI6Ii8xNTU1NDkxNzcvMzA2NjQ3NDQ0LWNiYTgxYmJkLWY2ODItNDYxMC04ZGE2LWM0OGNjNzFmNDA0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQxNTE0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTNhYzRlYWM2ZTlmMWMyNzUxNTQwZGYyODIxZGMwMWE0MDI5MTg1MzI2MzlkMTExZmU2NzIwY2U1ZGZhNTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kg5nNnQEYP7xR5eC0liEFxAaWApIzzvL1l6DzPUuvts)
> 
> Happy to update the documentation/prop name if you don't think that's clear enough?

Sorry, misunderstanding on my part based on how the height restraint prop works, the comment you've added to the code is perfectly fine :)  I will approve...

2024-02-21 15:15 UTC, GCHQ-Developer-299 approved these changes

2024-02-21 15:31 UTC, GCHQ-Developer-299 requested changes

2024-02-21 15:31 UTC, GCHQ-Developer-299 commented on packages/web-components/src/components/ic-dialog/test/basic/__snapshots__/ic-dialog.spec.ts.snap
Looks like you need to update the snapshot for this so that the tests pass!

2024-02-22 07:32 UTC, GCHQ-Developer-530 approved these changes

2024-02-22 08:56 UTC, GCHQ-Developer-465 approved these changes

2024-02-22 09:36 UTC, GCHQ-Developer-299 approved these changes

2024-02-22 09:36 UTC, merged