Canary/date input
mi6/ic-ui-kit pull request #1557
Opened 2024-02-22 09:42 UTC by jd239

## Summary of the changes
- Added new github actions for Cypress this includes:
  - Running Cypress tests only
  - Updating Cypress visual regression snapshots via CI
  - Uploading visual regression report if there are any errors
  - Updating folders names due to visual regression v2 update
- Threshold helper function which allows a 0 threshold value for CI but an updated threshold for local testing
- Date Input implementation for Canary release
- Jest/Puppeteer to Cypress component tests
- Updated ic-input-component-container for additional 'large' size
- Removal of screenshots from v1 visual regression within canary-web-components

## Related issue
#1364 

## Checklist
- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] All acceptance criteria reviewed and met. 
- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] Browser support tested (Chrome, Safari, Firefox and Edge).
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [x] All prop combinations work without issue.

2024-02-28 13:55 UTC, GCHQ-Developer-299 commented on packages/canary-react/cypress/screenshots/IcDateInput/IcDateInput.cy.tsx/IcDateInput -- renders (failed) (attempt 2).png
Should the screenshots for these failure attempts be included in the commit?

2024-02-28 13:55 UTC, GCHQ-Developer-299 commented on packages/canary-react/cypress/screenshots/IcDateInput/IcDateInput.cy.tsx/IcDateInput -- renders (failed) (attempt 2).png
Oh i see, they're added in commit 1 and removed in commit 4

2024-02-28 13:55 UTC, GCHQ-Developer-299 commented on packages/canary-web-components/src/utils/date-helpers.ts
> +    if (typeof date === "string") {
dunno how you feel about ternary operators but this if/else could be
```js
newDate = (typeof date === "string") ? new Date(date) : date;
```
i think.

2024-02-28 15:01 UTC, GCHQ-Developer-299 commented on packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx
> +      if (+this.day > this.MAX_DAY) {
Couple more opportunities to replace with ternary operators here. this.isValidDay and this.isValidMonth

2024-02-28 15:12 UTC, GCHQ-Developer-299 commented on packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx
> +    if (eventKey === "/" || eventKey === "-" || eventKey === ".") {
potentially could swap this for a switch statement where it's like 
```js
switch(eventKey) {
case "/":
case "-":
case ".":
  event.preventDefault();
  this.setPasteInvalidText();
  this.moveToNextInput(input);
case: "arrowright":
case: "arrowleft":
  event.preventDefault();
  ...
```
but i dunno what you think is more readable!

2024-03-01 14:36 UTC, GCHQ-Developer-299 approved these changes
Tested stories with keyboard and screenreader and all seemed functional :)

2024-03-04 08:26 UTC, GCHQ-Developer-299 approved these changes

2024-03-07 10:30 UTC, GCHQ-Developer-465 approved these changes

2024-03-07 10:31 UTC, GCHQ-Developer-299 approved these changes

2024-03-07 11:28 UTC, ad9242 requested changes
Should not be merged until date-picker component is also approved

2024-03-20 14:02 UTC, GCHQ-Developer-847 approved these changes

2024-03-20 15:51 UTC, merged