Ic page header cypress
mi6/ic-ui-kit pull request #1562
Opened 2024-02-23 12:48 UTC by mmb675

Complete Cypress tests for the Page Header, including end-to-end (e2e), accessibility, and visual regression tests.

## Summary of the changes
Tell us, in a few words, what the changes are.

## Related issue
Tell us the issue number. If suggesting an improvement or component, please discuss it with us in an issue first.

## Checklist
- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] All acceptance criteria reviewed and met. 
- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge).
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [ ] All prop combinations work without issue. 
- [ ] Changes to docs package checked and committed.
- [ ] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.

2024-03-05 10:43 UTC, GCHQ-Developer-530 reviewed
The cypress tests appear to be failing for this, I think the best bet is to remove all the cypress snapshots generated locally and to run the new update cypress visual regression test action so that the ci generates them

2024-03-05 11:00 UTC, gd2910 requested changes

2024-03-05 11:00 UTC, gd2910 commented on packages/react/src/component-tests/IcPageHeader/IcPageHeaderTestData.tsx
> +import React, { useRef, useState } from "react";
Unused, can be removed.

2024-03-05 11:00 UTC, gd2910 commented on packages/react/src/component-tests/IcPageHeader/IcPageHeader.cy.tsx
> +      testThreshold: DEFAULT_TEST_THRESHOLD + 0.05,
Please use the new method setThresholdBasedOnEnv for threshold on screenshots.

2024-03-05 11:00 UTC, gd2910 commented on packages/react/src/component-tests/IcPageHeader/IcPageHeader.cy.tsx
> +    cy.get("ic-page-header").invoke("css", "position", "null");
No assertion or snapshot to test after the invoke() command

2024-03-05 11:00 UTC, gd2910 commented on packages/react/src/component-tests/IcPageHeader/IcPageHeader.cy.tsx
> +    cy.viewport(1440, 590);
Where possible it's best to set the viewport before the mount, it's easier to review and can avoid breakpoint snaphots failing.

2024-03-05 11:18 UTC, jd239 requested changes
A few comments. 
Noticed the PR summary is not quite right. You can remove items from the checklist if they are not relevant for the PR if necessary.

2024-03-05 11:18 UTC, jd239 commented on packages/react/cypress-image-diff-screenshots/baseline/IcPageHeader.cy.tsx-dasktopOnlyAfterScroll.png
Typo in image name

2024-03-05 11:18 UTC, jd239 commented on packages/react/src/component-tests/IcPageHeader/IcPageHeader.cy.tsx
> +describe("IcPageHeader e2e, A11y and visual regression tests", () => {
Can this be updated to just `IcPageHeader` and the `it(` further down detail what the tests are. For example, the first test is just labelled `IcPageHeader`

2024-03-05 11:18 UTC, jd239 commented on packages/react/src/component-tests/IcPageHeader/IcPageHeader.cy.tsx
> +    cy.get("ic-page-header").invoke("css", "position", "absolute");
Saw this on the Cypress site but I do not think this is what we want because it changes the position from `sticky`.

2024-03-05 11:18 UTC, jd239 commented on packages/react/src/component-tests/IcPageHeader/IcPageHeader.cy.tsx
> +      name: "dasktopOnlyAfterScroll",
```suggestion
      name: "desktopOnlyAfterScroll",
```

2024-03-05 11:18 UTC, jd239 commented on packages/react/src/component-tests/IcPageHeader/IcPageHeader.cy.tsx
> +  it("without boarder page header", () => {
```suggestion
  it("without border page header", () => {
```

2024-03-05 11:18 UTC, jd239 commented on packages/react/src/component-tests/IcPageHeader/IcPageHeader.cy.tsx
> +      </IcPageHeader>
Move to TestData file to keep consistent with others

2024-03-05 11:18 UTC, jd239 commented on packages/react/src/component-tests/IcPageHeader/IcPageHeader.cy.tsx
> +    cy.viewport(1450, 500);
Can the test using this viewport be added to a new describe block and use the viewport within `beforeEach`?

2024-03-21 13:38 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcPageHeader/IcPageHeaderTestData.tsx
> +        <div style={{ margin: "10px" }}>
I think this margin is causing the page header to not show full width
```suggestion
        <div>
```

2024-03-21 13:41 UTC, GCHQ-Developer-530 commented
Looks like only the laptop loki test screenshots have been deleted in this PR, please can you delete the iphone7 loki screenshots as well?

2024-03-21 14:05 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcPageHeader/IcPageHeader.cy.tsx
> +  });
I think I've found a solution to the sticky page header screenshot issue - you can just clip the image 👍 
```suggestion
it("should stay at the top of the page if the sticky variant is used", () => {
    cy.viewport(1050, 450);
    mount(<ScrollStickyPageHeader />);
    cy.checkA11yWithWait();
    cy.scrollTo("bottom").checkHydrated("ic-button#end");
    cy.checkA11yWithWait();
    cy.compareSnapshot({
      name: "stickyVariant",
      testThreshold: setThresholdBasedOnEnv(0.02),
      cypressScreenshotOptions: {
        clip: {x: 0, y: 450, width: 1050, height: 600}
      },
    });
  });
```

2024-03-21 14:42 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcPageHeader/IcPageHeader.cy.tsx
> +  });
Solution for this sticky page header screenshot
```suggestion
  it("page header should not stay on top if prop use stickyDesktopOnly for viewport extra small", () => {
    cy.viewport("iphone-6")
    mount(<DesktopScrollablePageVariant />);
    cy.compareSnapshot({
      name: "desktopOnlyBeforeScroll",
      testThreshold: setThresholdBasedOnEnv(0.02),
      cypressScreenshotOptions: {
        capture: 'viewport'
      }
    });
    cy.scrollTo("bottom");
    cy.compareSnapshot({
      name: "desktopOnlyAfterScroll",
      testThreshold: setThresholdBasedOnEnv(0.02),
      cypressScreenshotOptions: {
        capture: 'viewport'
      }
    });
  });
```

2024-03-22 15:17 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcPageHeader/IcPageHeaderTestData.tsx
> +      <div style={{ margin: "10px" }}>
Margin needs to be removed so that page header is full width
```suggestion
      <div>
```

2024-03-22 16:17 UTC, gd2910 submitted a review, later dismissed

2024-03-25 12:39 UTC, GCHQ-Developer-530 approved these changes

2024-03-27 10:34 UTC, GCHQ-Developer-530 approved these changes

2024-03-27 11:49 UTC, GCHQ-Developer-465 approved these changes

2024-03-27 12:33 UTC, merged