1495 migrate loading indicator testing over to cypress
mi6/ic-ui-kit pull request #1567
Opened 2024-02-26 16:37 UTC by GCHQ-Developer-257

## Summary of the changes
Add cypress tests for loading indicator and remove the old a11y and e2e tests.

A spec test has been added to the Jest file to assert the default labelDuration value.

## Related issue
#1495 

## Checklist
- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] All acceptance criteria reviewed and met. 
- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] Browser support tested (Chrome, Safari, Firefox and Edge).
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [x] All prop combinations work without issue. 
- [x] Changes to docs package checked and committed.
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.

2024-02-27 12:40 UTC, GCHQ-Developer-299 commented on packages/react/cypress-image-diff-screenshots/baseline/IcLoadingIndicator.cy.tsx-[object Object].png
This file being called ...[object Object].png suggests it probably shouldn't be in here?

2024-03-04 10:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1567) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1567) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: GCHQ-Developer-257<br/>:x: github-actions[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=1567) it.</sub>

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/cypress-image-diff-screenshots/baseline/IcLoadingIndicator.cy.tsx-determinateLinear.png
I think now that you have the test determinateLinearsWith3Sizes, this one isn't needed as it's included there

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/cypress-image-diff-screenshots/baseline/IcLoadingIndicator.cy.tsx-determinateDarkCircularWithLabel.png
I think we can remove this dark circular one, it's covered by determinateDarkCircularWith3Sizes

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/cypress-image-diff-screenshots/baseline/IcLoadingIndicator.cy.tsx-determinateCircular.png
This can be removed too as it's covered by determinateCircularsWith3Sizes

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/cypress-image-diff-screenshots/baseline/IcLoadingIndicator.cy.tsx-determinateCircularDarkWithIcon.png
It would be good if we could clip this screenshot like we've done in the top nav cypress tests, there's a lot of empty space we don't need to capture

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/cypress-image-diff-screenshots/baseline/IcLoadingIndicator.cy.tsx-determinateCircularDarkWithIcon.png
This applies to any of the screenshots that don't fill most of the screen as well
- determinateCircularWithDescNoLabel
- determinateCircularWithIcon
- determinateCircularWithInnerLabel
- determinateLinearsDarkWith3Sizes

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcLoadingIndicator/IcLoadingIndicatorTestData.tsx
> +export const DeterminateCircularDarkLoadingIndWithLabel = (args: {
I think the name of this is misleading as it's actually applying appearance light
```suggestion
export const DeterminateCircularLightLoadingIndWithLabel = (args: {
```

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcLoadingIndicator/IcLoadingIndicatorTestData.tsx
> +export const DeterminateCircularDarkLoadingIndSizeSmallDefaultLarge = (args: {
```suggestion
export const DeterminateCircularLightLoadingIndSizeSmallDefaultLarge = (args: {
```

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcLoadingIndicator/IcLoadingIndicatorTestData.tsx
> +export const DeterminateCircularDarkLoadingIndIconNoLabel = (args: {
```suggestion
export const DeterminateCircularLightLoadingIndIconNoLabel = (args: {
```

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcLoadingIndicator/IcLoadingIndicatorTestData.tsx
> +export const DeterminateLinearDarkLoadingIndSizeDefaultLargeFull = (args: {
```suggestion
export const DeterminateLinearLightLoadingIndSizeDefaultLargeFull = (args: {
```

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcLoadingIndicator/IcLoadingIndicator.cy.tsx
> +  it("renders determinate dark circular with label", () => {
The test names should also be updated to say light instead of dark
```suggestion
  it("renders determinate light circular with label", () => {
```

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcLoadingIndicator/IcLoadingIndicator.cy.tsx
> +      name: "determinateDarkCircularWithLabel",
And the snapshot names should be updated too
```suggestion
      name: "determinateLightCircularWithLabel",
```

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcLoadingIndicator/IcLoadingIndicator.cy.tsx
> +  it("renders determinate dark circular with many sizes", () => {
```suggestion
  it("renders determinate light circular with many sizes", () => {
```

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcLoadingIndicator/IcLoadingIndicator.cy.tsx
> +      name: "determinateDarkCircularWith3Sizes",
```suggestion
      name: "determinateLightCircularWith3Sizes",
```

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcLoadingIndicator/IcLoadingIndicator.cy.tsx
> +  it("renders determinate dark circular icon size", () => {
```suggestion
  it("renders determinate light circular icon size", () => {
```

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcLoadingIndicator/IcLoadingIndicator.cy.tsx
> +      name: "determinateCircularDarkWithIcon",
```suggestion
      name: "determinateCircularLightWithIcon",
```

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcLoadingIndicator/IcLoadingIndicator.cy.tsx
> +  it("renders lots of determinate linear dark with many sizes", () => {
```suggestion
  it("renders lots of determinate linear light with many sizes", () => {
```

2024-03-05 07:32 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcLoadingIndicator/IcLoadingIndicator.cy.tsx
> +      name: "determinateLinearsDarkWith3Sizes",
```suggestion
      name: "determinateLinearsLightWith3Sizes",
```

2024-03-05 10:57 UTC, jd239 requested changes
Just a single comment from me

2024-03-05 10:57 UTC, jd239 commented on packages/docs/docs.json
This can be removed for the PR as it's just updating the docs datetime

2024-03-06 10:37 UTC, GCHQ-Developer-299 requested changes
Your commit messages are not using the correct scopes or describing their changes as per the CONTRIBUTING.md 

I would suggest git rebase --soft [the commit id before your changes] and remaking your commits to meet our contribution model.

2024-03-06 11:26 UTC, GCHQ-Developer-530 approved these changes

2024-03-06 11:28 UTC, GCHQ-Developer-299 approved these changes

2024-03-06 11:30 UTC, jd239 approved these changes

2024-03-06 11:31 UTC, merged