1560 chip accessibility improvements for icons
mi6/ic-ui-kit pull request #1573
Opened 2024-02-27 11:54 UTC by GCHQ-Developer-299

## Summary of the changes
Add aria labels or aria-hidden to storybook stories for IcChip. This will be replicated in the guidance site in a separate pull request.

## Related issue
#1560 

## Checklist
- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] All acceptance criteria reviewed and met. 
- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge).
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [ ] All prop combinations work without issue. 
- [ ] Changes to docs package checked and committed.
- [ ] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.

2024-02-27 13:05 UTC, GCHQ-Developer-530 approved these changes

2024-02-27 14:36 UTC, jd239 commented on packages/react/src/stories/ic-chip.stories.mdx
The changes look good. I'm wondering if it is worth changing the svg to a `SlottedSVG` and making sure the icon is still read out correctly. An SVG with slot in TS would cause an issue.

2024-02-27 14:37 UTC, jd239 requested changes
Just a small update. Other than that, looks good.

2024-02-28 10:56 UTC, jd239 approved these changes

2024-02-28 10:58 UTC, merged