Ic pagination cypress
mi6/ic-ui-kit pull request #1612
Opened 2024-02-29 13:26 UTC by mmb675

Complete Cypress Pagination Ticket: End-to-End, Regression, and Accessibility Tests.

## Summary of the changes
Tell us, in a few words, what the changes are.

## Related issue
Tell us the issue number. If suggesting an improvement or component, please discuss it with us in an issue first.

## Checklist
- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] All acceptance criteria reviewed and met. 
- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge).
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [ ] All prop combinations work without issue. 
- [ ] Changes to docs package checked and committed.
- [ ] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.

2024-02-29 13:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1612) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1612) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=1612) it.</sub>

2024-03-01 15:03 UTC, gd2910 requested changes

2024-03-05 10:33 UTC, jd239 submitted a review, later dismissed
A few comments

2024-03-19 12:55 UTC, gd2910 commented on packages/react/src/component-tests/IcPagination/IcPagination.cy.tsx
> +  it("reanders simple type pagination", () => {
```suggestion
  it("renders simple type pagination", () => {
```

2024-03-19 12:56 UTC, gd2910 commented on packages/react/src/component-tests/IcPagination/IcPagination.cy.tsx
> +  it("renader complex type pagination", () => {
```suggestion
  it("renders complex type pagination", () => {
```

2024-03-19 12:56 UTC, gd2910 commented on packages/react/src/component-tests/IcPagination/IcPagination.cy.tsx
> +describe("IcPagination e2e, A11y and visual regression tests", () => {
```suggestion
describe("IcPagination", () => {
```

2024-03-19 12:58 UTC, gd2910 commented on packages/react/src/component-tests/IcPagination/IcPagination.cy.tsx
Most snapshots need a top margin to show the full focused element.

2024-03-19 13:03 UTC, gd2910 commented on packages/react/src/component-tests/IcPagination/IcPagination.cy.tsx
When running locally I'm getting a lot of visual regression failures. On checking the 'Image Diff report' there are a lot of variances in passing and failing tests. In addition to above comments from @jd239, all of the threshold numbers are now +0.02?

2024-03-19 15:56 UTC, mmb675 commented on packages/react/src/component-tests/IcPagination/IcPagination.cy.tsx
it is now 0.02  change to new screenshot test.

2024-03-27 11:40 UTC, GCHQ-Developer-530 approved these changes

2024-03-27 12:16 UTC, gd2910 approved these changes

2024-03-27 12:20 UTC, merged