Feat/canary css workflow
mi6/ic-ui-kit pull request #1642
Opened 2024-03-07 11:24 UTC by jd239

## Summary of the changes
This updates removes the local canary CSS files in favour of the core web-component files. This change will keep canary in sync with the latest CSS changes as well as make it easier to maintain by having a single source of truth. The npm script for Canary React will now take the CSS files from canary once they have been copied across as part of the build process. 

This also prevents a mismatch of core and canary packages as the styling on canary will be the most up to date no matter what web-components version the consumer is using. 

## Related issue
N/A

## Checklist
N/A

2024-03-07 11:57 UTC, GCHQ-Developer-112 requested changes

2024-03-07 11:57 UTC, GCHQ-Developer-112 commented on packages/canary-web-components/src/global/variables.css
There's at least one data table specific variable in this css file

2024-03-07 15:38 UTC, GCHQ-Developer-112 approved these changes
Happy to approve this PR assuming that the data tables variable - `--ic-table-row-selected` is moved over to the core variables.css file along with any other canary-specific styling that may be on the `data-tables-v2-new` branch

2024-03-07 15:59 UTC, jd239 commented
> Happy to approve this PR assuming that the data tables variable - `--ic-table-row-selected` is moved over to the core variables.css file along with any other canary-specific styling that may be on the `data-tables-v2-new` branch

Any other styling is component specific and is held within a separate CSS file.

2024-03-08 08:37 UTC, ad9242 requested changes
also happy to approve once --ic-table-row-selected is added to the variables.css in the web-components package

2024-03-08 11:38 UTC, ad9242 approved these changes

2024-03-08 11:39 UTC, GCHQ-Developer-112 approved these changes

2024-03-08 12:18 UTC, merged