1520 expandable cards a11y
mi6/ic-ui-kit pull request #1644
Opened 2024-03-07 14:07 UTC by GCHQ-Developer-741

## Summary of the changes
- Updated card component to utilise a native button instead of ic-button, since shadowDOM components can't utilise aria-controls attributes
- Updated the card cypress tests accordingly, combining the expanded tests into one and generating new snapshots

## Related issue
#1520

## Checklist
- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] All acceptance criteria reviewed and met. 
- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] Browser support tested (Chrome, Safari, Firefox and Edge).
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [x] All prop combinations work without issue. 
- [x] Changes to docs package checked and committed.
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.

2024-03-07 14:47 UTC, GCHQ-Developer-299 requested changes

2024-03-07 14:47 UTC, GCHQ-Developer-299 commented on packages/web-components/src/components/ic-card/ic-card.tsx
> +                  aria-expanded={this.areaExpanded}
I think you need to set this to explictly "true" or "false" based on this.areaExpanded. Currently when I use Voiceover, it doesn't give me any suggestion that the button expands:
![Screenshot 2024-03-07 at 14 42 08](https://github.com/mi6/ic-ui-kit/assets/111292477/875328f4-7f55-489e-87ee-105b5fe57e4a)

2024-03-08 14:11 UTC, GCHQ-Developer-299 commented on packages/web-components/src/components/ic-card/ic-card.tsx
> +                  aria-expanded={this.areaExpanded ? true : false}
Change this to
```js
aria-expanded={this.areaExpanded ? "true" : "false" }
```

2024-03-11 11:53 UTC, GCHQ-Developer-299 approved these changes

2024-03-11 13:18 UTC, GCHQ-Developer-465 approved these changes

2024-03-11 13:43 UTC, merged