feat(react): added tabbing and other interactions into cypress tests …
mi6/ic-ui-kit pull request #1685
Opened 2024-03-21 12:39 UTC by gd2910

…suite

## Summary of the changes
Previously cypress did not support tabbing(keyboard), adding cypress-real-events allows us to test the components in a more comprehensive manner in which our users would interact with them

## Related issue
#1538 

## Checklist

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.

2024-03-21 15:30 UTC, ad9242 requested changes

2024-03-21 15:30 UTC, ad9242 commented on packages/react/cypress/support/index.ts
how come the quotes have changed?

2024-03-21 15:30 UTC, ad9242 commented on packages/react/package-lock.json
> +    "node_modules/@ukic/web-components": {
i'd be tempted to remove this, as it wasn't previously in the file. I would only push the changes for the added package

2024-03-21 15:40 UTC, GCHQ-Developer-847 submitted a review, later dismissed

2024-03-22 12:57 UTC, gd2910 commented on packages/react/cypress/support/index.ts
My editor was set to use the prettier.json settings in packages/web-components, which has singleQuotes set to true, prettier:fix doesn't cover this file so it was never being fixed. Sorted now.

2024-03-22 13:26 UTC, GCHQ-Developer-299 approved these changes

2024-03-22 14:55 UTC, GCHQ-Developer-847 approved these changes

2024-03-22 14:56 UTC, merged