1337 pagination bar fix
mi6/ic-ui-kit pull request #1725
Opened 2024-03-28 10:45 UTC by ad9242

## Summary of the changes
Fixes Pagination bar not updating when props change

## Related issue
#1337 

## Checklist

### General 

- [ ] Changes to docs package checked and committed.
- [ ] All acceptance criteria reviewed and met. 

### Testing

- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 

### Accessibility 

- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content.
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] All prop combinations work without issue. 
- [ ] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.

2024-04-09 11:44 UTC, jd239 requested changes
Looks good. A few formatting issues but functionality works as expected.

2024-04-10 09:17 UTC, gd2910 commented on packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx
>  })
```suggestion
})

```

2024-04-10 09:17 UTC, gd2910 commented on packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx
Remove empty lines?

2024-04-10 09:17 UTC, gd2910 commented on packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx
Some props need to be alphabetised

2024-04-10 09:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1725) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1725) before we can accept your contribution.<br/>**7** out of **8** committers have signed the CLA.<br/><br/>:white_check_mark: GCHQ-Developer-741<br/>:white_check_mark: ad9242<br/>:white_check_mark: gd2910<br/>:white_check_mark: jd239<br/>:white_check_mark: GCHQ-Developer-847<br/>:white_check_mark: GCHQ-Developer-530<br/>:white_check_mark: GCHQ-Developer-112<br/>:x: mmb675<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=1725) it.</sub>

2024-04-11 09:30 UTC, gd2910 approved these changes

2024-04-16 14:58 UTC, ad9242 commented
replaced by #1770

2024-04-16 14:58 UTC, closed without merging