1606 ic UI kit transition all workflow actions to run on node 20
mi6/ic-ui-kit pull request #1761
Opened 2024-04-12 12:46 UTC by gd2910

## Summary of the changes
Update all node- version references from 18 -> 20

## Related issue
#1606 

## Checklist

### General 

- [ ] Changes to docs package checked and committed.
- [ ] All acceptance criteria reviewed and met.

2024-04-12 13:04 UTC, GCHQ-Developer-299 submitted a review, later dismissed

2024-04-12 14:39 UTC, jd239 commented
I think this ticket involves updating the github action rather than the node version we have explicitly set. So for example, update actions/checkout@v3 to actions/checkout@v4

2024-04-12 14:40 UTC, jd239 requested changes
Just added a single comment

2024-04-15 09:35 UTC, jd239 approved these changes

2024-04-15 10:07 UTC, GCHQ-Developer-112 approved these changes

2024-04-15 10:08 UTC, merged