Pagination bar fixes
mi6/ic-ui-kit pull request #1843
Opened 2024-05-03 15:50 UTC by ad9242

## Summary of the changes
Fixes some issues spotted in storybook docs. This has also led to some prop name changes, but these are not deemed breaking changes as the component is still in canary
Updates Cypress tests
Updates spec test and storybook docs

## Checklist

### General 

- [ ] Changes to docs package checked and committed.
- [ ] All acceptance criteria reviewed and met. 

### Testing

- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 

### Accessibility 

- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content.
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] All prop combinations work without issue. 
- [ ] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [ ] Controlled and uncontrolled input components tested.

2024-05-07 13:00 UTC, GCHQ-Developer-299 approved these changes

2024-05-07 14:51 UTC, jd239 requested changes
Checked if adding the 'BREAKING CHANGE' message via Commitizen updates the major version number and it doesn't due to it being a prerelease so think it will be good to add a note of the breaking change in the commit message.

2024-05-07 14:51 UTC, jd239 commented on packages/canary-react/src/stories/ic-pagination-bar.stories.mdx
> +The example belows uses the `data` pagination range label type. The range is updated when the page is changed.
```suggestion
The example below uses the `data` pagination range label type. The range is updated when the page is changed.
```

2024-05-07 14:51 UTC, jd239 commented on packages/canary-react/src/stories/ic-pagination-bar.stories.mdx
> +If the pagination bar becomes clutted due to the number of pagination elements displayed, the items per page label can be hidden by setting the `hideRangeLabel` prop to `true`.
```suggestion
If the pagination bar becomes clutted due to the number of pagination elements displayed, the range label can be hidden by setting the `hideRangeLabel` prop to `true`.
```

2024-05-07 14:51 UTC, jd239 commented on packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.stories.mdx
> +The example belows uses the `data` pagination range label type. The range is updated when the page is changed.
```suggestion
The example below uses the `data` pagination range label type. The range is updated when the page is changed.
```

2024-05-07 14:51 UTC, jd239 commented on packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx
> +  @Prop() rangeItemLabel?: string = "Item";
I keep on reading this prop in my head and wondering if it should be `range-label-item / rangeLabelItem`? Will let you decide...

2024-05-08 08:24 UTC, jd239 approved these changes

2024-05-08 08:25 UTC, merged