fix(web-components): css changes
mi6/ic-ui-kit pull request #1894
Opened 2024-05-21 13:04 UTC by gd2910

css rulesets for forced-colors added

## Summary of the changes
When using forced-colors there were no discernible differences between toggled states, this adds the `Highlight` state to each of the applicable toggle-buttons

## Related issue
#1893

2024-05-21 14:53 UTC, GCHQ-Developer-112 commented
Please make your commit message more descriptive of the change you've made

2024-05-22 07:15 UTC, ad9242 requested changes

2024-05-22 07:15 UTC, ad9242 commented on packages/web-components/src/components/ic-toggle-button/ic-toggle-button.css
> +    background-color: Highlight;
```suggestion
    background-color: GrayText;
```
in order to match checkbox\radio?

2024-05-22 11:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1894) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1894) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: gd2910<br/>:x: github-actions[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=1894) it.</sub>

2024-05-22 11:18 UTC, GCHQ-Developer-299 approved these changes

2024-05-22 11:48 UTC, GCHQ-Developer-299 approved these changes

2024-05-22 11:51 UTC, ad9242 approved these changes

2024-05-22 12:15 UTC, merged