test(react): adds support for high contrast mode testing
mi6/ic-ui-kit pull request #1895
Opened 2024-05-21 15:28 UTC by ad9242

## Summary of the changes
Adds support for testing components with forced-colors enabled in cypress.
Tests added for textfield

## Related issue
N/A

## Checklist

### Testing

- [ ] Relevant unit tests and visual regression tests added.

2024-05-21 15:38 UTC, gd2910 requested changes

2024-05-21 15:38 UTC, gd2910 commented on packages/react/cypress/support/commands.ts
> +       * Disble forced colours
```suggestion
       * Disable forced colours
```

2024-05-22 06:33 UTC, GCHQ-Developer-530 commented on packages/react/src/component-tests/IcTextField/IcTextField.cy.tsx
> +describe.only("IcTextField visual regression in high contrast mode", () => {
```suggestion
describe("IcTextField visual regression in high contrast mode", () => {
```

2024-05-22 07:04 UTC, GCHQ-Developer-530 approved these changes

2024-05-22 07:47 UTC, gd2910 approved these changes

2024-05-22 08:07 UTC, GCHQ-Developer-299 approved these changes

2024-05-22 08:07 UTC, merged