1675 create all variant types for icon button
mi6/ic-ui-kit pull request #1925
Opened 2024-05-28 13:48 UTC by gd2910

## Summary of the changes
All variant types added for icon variant of ic-button

## Related issue
#1675

2024-05-28 15:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1925) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=1925) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: gd2910<br/>:x: github-actions[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=1925) it.</sub>

2024-05-29 13:05 UTC, GCHQ-Developer-299 submitted a review, later dismissed

2024-05-29 13:24 UTC, jd239 requested changes
A few updates. Good to see icon button in different variants.

2024-05-29 13:24 UTC, jd239 commented on packages/react/src/component-tests/IcButton/IcButtonTestData.tsx
> +            props.appearance === "light" || props.appearance === "light"
This OR statement is checking the same thing

2024-05-29 13:24 UTC, jd239 commented on packages/react/src/component-tests/IcButton/IcButtonTestData.tsx
> +            props.appearance === "light" || props.appearance === "light"
This OR statement is checking the same thing

2024-05-29 13:24 UTC, jd239 commented on packages/react/src/stories/ic-button.stories.mdx
> +          backgroundColor: props.appearance === "light" || props.appearance === "light"  ? "#2c2f34" : "#fff",
Same OR statement being checked

2024-05-29 13:24 UTC, jd239 commented on packages/react/src/stories/ic-button.stories.mdx
> +          padding: props.appearance === "light" || props.appearance === "light"  ? "6px 10px" : "none",
Same OR checks

2024-05-29 13:24 UTC, jd239 commented on packages/react/src/stories/ic-button.stories.mdx
> +export const props = {
Can this not be imported from test data file? Will make it easier to update if required down the line.

2024-05-29 13:53 UTC, jd239 submitted a review, later dismissed

2024-05-29 14:06 UTC, jd239 approved these changes

2024-05-29 14:09 UTC, merged