1970 canary date component playgrounds
mi6/ic-ui-kit pull request #2032
Opened 2024-06-19 11:10 UTC by GCHQ-Developer-530

## Summary of the changes
Add playground stories for date input and date picker

Min and max playground stories don't update for date input or date picker - Ticket to be created
openAtDate seems to crash my browser window - Can anyone checking this PR test this and if it happens for others then a ticket needs to be created for that too

## Related issue
Part of #1970

## Checklist

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.

2024-06-20 12:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=2032) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=2032) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=2032) it.</sub>

2024-06-21 10:27 UTC, GCHQ-Developer-299 approved these changes

2024-06-24 15:39 UTC, ad9242 requested changes
i think it would be quite nice to make value a string, then we could test with "-" separator too

2024-06-24 15:41 UTC, ad9242 commented
There seems to be a problem where, if you have a value set, changing the date-format clears the field. I'd expect it to update the value, but that should be a new ticket as it doesn't support it at the moment (would need changes to input & picker i think)

2024-06-25 06:30 UTC, GCHQ-Developer-530 commented
> There seems to be a problem where, if you have a value set, changing the date-format clears the field. I'd expect it to update the value, but that should be a new ticket as it doesn't support it at the moment (would need changes to input & picker i think)

https://github.com/mi6/ic-ui-kit/issues/2056 created

2024-06-25 08:39 UTC, ad9242 requested changes
I think the blanking of the value may be a bigger issue, than just changing the date format. it seems to be that, if you have entered a value in the picker\input and then change a storybook control eg, disabled, then it blanks the value. I think this is because it re-uses the value from the storybook control.

you can keep them in sync with https://storybook.js.org/docs/addons/addons-api#useargs 
see checkbox playground for an example

2024-06-25 09:02 UTC, GCHQ-Developer-530 commented
> I think the blanking of the value may be a bigger issue, than just changing the date format. it seems to be that, if you have entered a value in the picker\input and then change a storybook control eg, disabled, then it blanks the value. I think this is because it re-uses the value from the storybook control.
> 
> you can keep them in sync with https://storybook.js.org/docs/addons/addons-api#useargs see checkbox playground for an example

Ah brilliant, thank you. I've updated it

2024-06-26 12:01 UTC, ad9242 requested changes

2024-06-26 12:01 UTC, ad9242 commented on packages/canary-react/src/stories/ic-date-input.stories.mdx
> +          value={value}
think you need to add an onIcChange event that calls updateArgs with the new value, to keep the control in sync:

```
onIcCheck={(ev) => updateArgs({ value: ev.detail.value })}
```

2024-06-26 14:42 UTC, ad9242 requested changes

2024-06-26 14:42 UTC, ad9242 commented on packages/canary-react/src/stories/ic-date-picker.stories.mdx
> +        updateArgs({ value: formattedDate});
sorry, could this also handle setting an empty string when the value is cleared?

2024-07-01 07:10 UTC, ad9242 approved these changes

2024-07-01 15:38 UTC, GCHQ-Developer-847 approved these changes

2024-07-02 06:32 UTC, merged