feat(web-components): add large variant to status tag
mi6/ic-ui-kit pull request #2034
Opened 2024-06-19 13:14 UTC by GCHQ-Developer-773

added large variant to status tag and added large to storybook, and included large and large
outlined in css for status    tags

## Summary of the changes
Tell us, in a few words, what the changes are.

## Related issue
#239

## Checklist

### General 

- [ ] Changes to docs package checked and committed.
- [/ ] All acceptance criteria reviewed and met. 

### Testing

- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 

### Accessibility 

- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [/ ] Page can be zoomed to 400% with no loss of content. 
- [ /] Screen magnifier used with no issues. 
- [/ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [/ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [/ ] Windows High Contrast mode tested with no loss of content.
- [/ ] System light and dark mode tested with no loss of content.
- [/ ] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] All prop combinations work without issue. 
- [ ] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [ ] Controlled and uncontrolled input components tested.

2024-06-19 13:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=2034) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=2034) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=2034) it.</sub>

2024-06-19 21:59 UTC, GCHQ-Developer-112 commented on packages/web-components/src/components/ic-status-tag/ic-status-tag.tsx
> -            ["small"]: small || size === "small",
Some, if not all of this line should still be in the code. Using the deprecated prop: `small` should still have an effect on the size of the status tag for the time being. This prop will be removed in V3

2024-06-19 21:59 UTC, GCHQ-Developer-112 commented on packages/web-components/src/components/ic-status-tag/ic-status-tag.tsx
> +
Please remove these extra lines

2024-06-19 22:02 UTC, GCHQ-Developer-112 commented
Sorry, just realised that this is a draft PR so you may already be working to address the comments above. Please add a story to the React storybook if you're not already working on this

2024-06-28 14:14 UTC, GCHQ-Developer-112 requested changes
Looks good overall!
Please can you add a visual regression Cypress test for the new size variant

2024-06-28 14:14 UTC, GCHQ-Developer-112 commented on packages/react/src/stories/ic-status-tag.stories.mdx
> +  </Story>
Please can you combine this into one 'Sizes story' - similar to this [ic-button size story](https://mi6.github.io/ic-ui-kit/branches/develop/web-components/?path=/story/web-components-button--size). This applies to the web components storybook as well

2024-07-02 14:16 UTC, GCHQ-Developer-112 requested changes
One small change needed, then all good for approval 🌟

2024-07-02 14:16 UTC, GCHQ-Developer-112 commented on packages/web-components/src/components/ic-status-tag/ic-status-tag.css
> +.large {
Please remove this duplicate CSS style

2024-07-02 14:17 UTC, GCHQ-Developer-530 commented
Please can you update both web components and react playground stories to have large as a size option?

2024-07-09 17:52 UTC, GCHQ-Developer-773 commented
@GCHQ-Developer-530 all sizes can be both in both stories under the sizes story. Any issues just let me know :)

2024-07-10 06:50 UTC, GCHQ-Developer-530 commented
> @GCHQ-Developer-530 all sizes can be both in both stories under the sizes story. Any issues just let me know :)

It needs updating in the playground story as well so we can see the large variant. Should just be a case of adding large as an option for this line: 
```
options: [
          "default", "small"
        ],
```

2024-07-10 08:08 UTC, GCHQ-Developer-530 submitted a review, later dismissed

2024-07-10 13:51 UTC, GCHQ-Developer-530 approved these changes

2024-07-11 10:35 UTC, GCHQ-Developer-112 approved these changes

2024-07-11 12:12 UTC, merged