662 review prop state names
mi6/ic-ui-kit pull request #2086
Opened 2024-07-02 09:58 UTC by GCHQ-Developer-530

## Summary of the changes
Accordion group and footer link group “group-title” renamed to “label”, badge “text-label” renamed to “label”, empty state “body-max-lines” renamed to “max-lines”, input label “error” renamed to “status” with error as an option, pagination “boundary-count” and “adjacent-count” renamed to “boundary-page-count” and “adjacent-page-count”, search bar and select “disable-filter” renamed to “disable-auto-filtering”, search bar “hint-text” renamed to “assistive-hint-text”, step props had the word “step” removed from the start e.g “step-status” renamed to “status”, toggle button “toggle-checked” renamed to “checked”.

## Related issue
#662 

## Checklist

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.

2024-07-02 09:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=2086) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=2086) before we can accept your contribution.<br/>**9** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: GCHQ-Developer-112<br/>:white_check_mark: GCHQ-Developer-530<br/>:white_check_mark: GCHQ-Developer-741<br/>:white_check_mark: ad9242<br/>:white_check_mark: GCHQ-Developer-299<br/>:white_check_mark: gd2910<br/>:white_check_mark: MI6-286<br/>:white_check_mark: GCHQ-Developer-847<br/>:white_check_mark: MI6-255<br/>:x: github-actions[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=2086) it.</sub>

2024-07-05 17:12 UTC, GCHQ-Developer-847 requested changes
Looks like some of the old prop names have possibly sneaked in via a rebase - there are some in a few of the playground stories for the components :)

Otherwise looks really good 👏

2024-07-08 11:48 UTC, GCHQ-Developer-847 approved these changes

2024-07-09 09:45 UTC, GCHQ-Developer-847 approved these changes

2024-07-09 11:56 UTC, ad9242 requested changes

2024-07-09 11:56 UTC, ad9242 commented on packages/web-components/.loki/reference/chrome_iphone7_Web_Components_Stepper_Without_headings.png
can this loki image be removed?

2024-07-09 11:56 UTC, ad9242 commented on packages/web-components/.loki/reference/chrome_laptop_Web_Components_Stepper_Without_headings.png
remove this one too?

2024-07-09 14:00 UTC, ad9242 approved these changes

2024-07-09 14:06 UTC, GCHQ-Developer-847 approved these changes

2024-07-09 14:08 UTC, merged