Feat(infra): add cspell to lint grammar
mi6/ic-ui-kit pull request #2096
Opened 2024-07-03 15:19 UTC by evenstensberg

## Summary of the changes
Integrates cspell to the repo

## Related issue
#2093 

## Checklist

### General 

- [ ] Changes to docs package checked and committed.
- [ ] All acceptance criteria reviewed and met. 

### Testing

- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 

### Accessibility 

- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content.
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] All prop combinations work without issue. 
- [ ] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [ ] Controlled and uncontrolled input components tested.

2024-07-03 18:58 UTC, GCHQ-Developer-112 commented
Hi @evenstensberg, thank you for your contribution! Please have a read of our [CONTRIBUTING.md](https://github.com/mi6/ic-ui-kit/blob/main/CONTRIBUTING.md#git-commit) for info on how to format commits in the `ic-ui-kit` repo

2024-07-03 19:50 UTC, evenstensberg commented
@GCHQ-Developer-112 will fix commits tomorrow 👍🏾

2024-07-04 16:22 UTC, GCHQ-Developer-112 commented
> @GCHQ-Developer-112 will fix commits tomorrow 👍🏾
> 
> Edit: Do I also need to amend the individual commits? If you merge this, you can just have one commit which is the PR title.
> 
> 2nd edit: commitlinting done, waiting for feedback about merging 1st commit or both of them in this pr

Hi @evenstensberg, please create a commit for each scope - scoping commits correctly is important for our release process and for an accurate record of changes in the CHANGELOG.md

2024-07-04 16:25 UTC, evenstensberg commented
@GCHQ-Developer-112 okay. Maybe we should merge the main commit first (integration of cspell) and start linting each mono-repo package in a separate pr?

2024-07-04 16:27 UTC, GCHQ-Developer-112 commented
> @GCHQ-Developer-112 okay. Maybe we should merge the integration of cspell first, then the fixes of spelling in seperate prs?

One PR with multiple commits is fine, given that the work is related. It makes it easier for us to review and keep track of the changes related to the spell checker

2024-07-04 16:30 UTC, GCHQ-Developer-112 commented on package.json
> +    "cspell": "^8.10.0"
Please make this a dev dependency instead

2024-07-04 16:34 UTC, GCHQ-Developer-112 commented on .cspell.json
> +        "destuctive"
Some of these words should be removed: e.g. "destuctive", "typograpghy", "GHSA" etc.

2024-07-04 20:28 UTC, evenstensberg commented
@GCHQ-Developer-112 All source code is now linted. FYI, you might need to update the snapshots that contain wrong wording.

I imagine this will take some time to review, so here's some more information that's good to know:


- The "words" prop in the cspell json file contains all the words cspell didnt find. After you've reviewed, we can gradually remove some words if you find any wrong ones.
- After reviewing the code, update snapshots and do tests on this branch/PR.


Let me know if you have any questions.

2024-07-04 20:30 UTC, GCHQ-Developer-112 commented
Hi @evenstensberg, I can see you've made a commit per word added to `.cspell.json`. This isn't needed. For this PR, you only need 5 commits as the changes are in 5 scopes: `root`, `web-components`, `react`, `canary-web-components` and `canary-react`. Please squash all the commits within the same scope into one commit e.g. all the changes in the root directory should be in one commit with a commit message that summarises the changes made within the root directory

2024-07-04 20:34 UTC, evenstensberg commented
@GCHQ-Developer-112 Okay. I thought it would be better for you to review. If one word is wrong, we can just revert the word  along with the word fix. Fixing this tomorrow.

2024-07-04 20:42 UTC, GCHQ-Developer-112 commented
> @GCHQ-Developer-112 Okay. I thought it would be better for you to review. If one word is wrong, we can just revert the word along with the word fix. Fixing this tomorrow.

Ah no. Having this many commits makes it harder to review as part of our review process is making sure that the changes in the commits are scoped correctly. If there are any changes that need to be made, I advise using an [interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)

2024-07-04 21:05 UTC, evenstensberg commented
@GCHQ-Developer-112 Done rebasing :)

2024-07-05 10:56 UTC, GCHQ-Developer-112 commented
> @GCHQ-Developer-112 Done rebasing :)

Thank you for making these changes. It's not quite ready to be approved yet. The commits are still not scoped correctly. Each scoped commit should only include changes related to the associated directory or sub-directory. For example, in the screenshot below, is a commit you've scoped to `canary-react`. In this commit, there should only be changes made within the `canary-react` sub-directory.
<img width="1038" alt="Screenshot 2024-07-05 at 11 43 56" src="https://github.com/mi6/ic-ui-kit/assets/113986285/47320c7c-1797-404b-b251-130723756f99">

Please can you also clean up the commit message. Currently where the commits have been squashed, the previous commit messages have been added. They are not needed. My apologies, I should have said when you do the interactive rebase and squash the commits, it's best to pick the fixup option so the commit messages aren't melded together.

2024-07-05 11:09 UTC, GCHQ-Developer-112 requested changes

2024-07-05 11:09 UTC, GCHQ-Developer-112 commented on .cspell.json
> +      "necolas"
Please remove the following words as they are incorrectly spelt: "desending", "merker", "connnector", "architechtural"

With the use of the lorem ipsum cspell dictionary, can the lorem ipsum words in this list be taken out? Are there other words that can be taken out now that you've installed the relevant dictionary e.g. is htmlFor covered in the HTML dictionary?

2024-07-08 07:41 UTC, GCHQ-Developer-112 commented
Closing as it's a duplicate PR (new PR: #2115)

2024-07-08 07:41 UTC, closed without merging