[ic-data-tables]: Truncation and text wrap functionality
mi6/ic-ui-kit pull request #2138
Opened 2024-07-11 10:47 UTC by jd239

## Summary of the changes
Truncation and text wrap functionality added to data tables. The new functionality includes:
- Updates to `ic-data-table`
- New Cypress tests
- New VR tests
- Updates to typography and tooltip
- CSS data table updates
- Updated storybook
- Updated types

## Related issue
#1003 

## Checklist

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 

### Accessibility 

- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content.
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] All prop combinations work without issue. 
- [ ] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [ ] Controlled and uncontrolled input components tested.

2024-07-17 07:31 UTC, GCHQ-Developer-112 requested changes
Hefty piece of work - well done! This was just the first round of reviewing. There's still more I need to check over but have a left a few comments in the meantime

2024-07-17 08:01 UTC, GCHQ-Developer-112 commented
Spotted some issues in Storybook

1. **Related to data table with pagination:** The ellipsis on truncated text is no longer present if the number of items is more than 5 e.g. 10 or 15 items and you go forward to the next page and then backwards to the previous page

https://github.com/user-attachments/assets/d32cf273-0f2e-4dbe-a577-394fdf29b61f

2. **Related to showHide truncation pattern:** When the text has enough space to be shown in full, it is still truncated. There is also a delay between changing the row height and the "see more" button appearing. This is a bit of a worry for data-dense data tables.

https://github.com/user-attachments/assets/4f04466c-78ee-45e8-abac-73991e3d8537

2024-07-18 13:10 UTC, jd239 commented on packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
> +     */
Removed

2024-07-18 13:34 UTC, jd239 commented on packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
> +    //TODO: Update function to accept value to replace getCellAlignment function
Nope. Removed.

2024-07-18 14:49 UTC, jd239 commented
>Related to showHide truncation pattern: When the text has enough space to be shown in full, it is still truncated. There is also a delay between changing the row height and the "see more" button appearing. This is a bit of a worry for data-dense data tables.

The issue with see more/see less is that I need the data to render before calculating whether it needs the show/hide button. Might be worth a discussion to figure out what is possible to make it a smoother experience.

2024-07-22 14:05 UTC, ad9242 requested changes

2024-07-23 08:42 UTC, jd239 commented on packages/canary-react/src/stories/ic-data-table.stories.mdx
> +If there is a certain row or column that should be exempt from truncation, then a property can either be added to the row or the column object, named `textWrap`. Anything this is applied to will igno
This has been amended and moved below text wrap

2024-08-06 07:21 UTC, GCHQ-Developer-112 approved these changes
As discussed

2024-08-08 07:14 UTC, ad9242 requested changes
There are some very high thresholds for some of the tests - some 30%+ & one is 49%. Could you just check over them, please?

2024-08-12 14:08 UTC, jd239 commented on packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
>    @Listen("icTableDensityUpdate")
This comes from Data table title bar: https://github.com/mi6/ic-ui-kit/blob/canary/data-tables-truncation-new/packages/canary-web-components/src/components/ic-data-table-title-bar/ic-data-table-title-bar.tsx#L58

2024-08-12 14:08 UTC, jd239 commented on packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
> +  @Listen("icItemsPerPageChange")
This comes from the pagination-bar: https://github.com/mi6/ic-ui-kit/blob/canary/data-tables-truncation-new/packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx#L168

2024-08-13 06:59 UTC, GCHQ-Developer-530 requested changes
This looks really good! Just had a look through and the only thing I've noticed is that the see more/see less pattern can be a bit temperamental on smaller screens. The department column seems to work perfectly adding the ellipsis and the see more button stays inside the column width. But name and job title sometimes get cut off. 
<img width="200" alt="Screenshot 2024-08-13 at 07 56 06" src="https://github.com/user-attachments/assets/e5645ef9-9233-438d-96f0-130e462e6bc2">
<img width="200" alt="Screenshot 2024-08-13 at 07 55 49" src="https://github.com/user-attachments/assets/689f47e6-ec79-42b8-8f56-c2b8df162b7d">

2024-08-14 14:07 UTC, GCHQ-Developer-299 commented on packages/canary-react/cypress-image-diff-screenshots/baseline/IcDataTable.cy.tsx-density-dense.png
The text in Last name overflows and is cut off - compared to the [Dense Storybook story](https://mi6.github.io/ic-ui-kit/branches/canary/data-tables-truncation-new/canary-react/?path=/story/react-components-data-table--dense) where the text wraps happily. Is the behaviour in this screenshot deliberate?

2024-08-15 10:03 UTC, GCHQ-Developer-299 submitted a review, later dismissed

2024-08-15 11:31 UTC, ad9242 requested changes

2024-08-15 11:31 UTC, ad9242 commented on packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
> +   * The `tooltip` truncation pattern allows the overflowing text to be seen in a tooltip. The `showHide` truncation pattern allows the overflowing text to be shown and hidden using the ic-typography
```suggestion
   * The `tooltip` truncation pattern allows the overflowing text to be seen in a tooltip. The `show-hide` truncation pattern allows the overflowing text to be shown and hidden using the ic-typography "See more"/"See less" buttons.
```

string should be kebab-case

2024-08-15 14:10 UTC, GCHQ-Developer-530 approved these changes

2024-08-15 14:11 UTC, GCHQ-Developer-299 approved these changes

2024-08-15 14:15 UTC, ad9242 approved these changes

2024-08-15 14:16 UTC, merged