chore(root): update husky
mi6/ic-ui-kit pull request #2232
Opened 2024-07-28 15:57 UTC by evenstensberg

## Summary of the changes
At [webpack contrib](https://github.com/webpack-contrib/html-loader/pull/523) we upgrade husky to the lts. The new version is a bit faster than the old one and automatically installs the deps without need of npx.

## Related issue
- https://github.com/typicode/husky/releases/tag/v9.1.1
- https://github.com/typicode/husky/releases/tag/v9.0.1
## Checklist

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [x] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.

2024-07-29 08:52 UTC, GCHQ-Developer-530 commented on .husky/pre-commit
> +lint-staged
I think this still needs to be `npx lint-staged`. I ran this locally and got the error: 
".husky/pre-commit: 15: lint-staged: not found"

2024-07-29 10:34 UTC, GCHQ-Developer-530 approved these changes

2024-08-07 15:10 UTC, jd239 commented on README.md
This has been updated further here: https://github.com/mi6/ic-ui-kit/pull/2236/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 so can this update be removed from this PR.

2024-08-07 15:10 UTC, jd239 requested changes
Just a single comment. Thanks.

2024-08-08 06:47 UTC, GCHQ-Developer-530 approved these changes

2024-08-09 08:37 UTC, jd239 approved these changes

2024-08-09 08:38 UTC, merged