2072 sizing consistency across component library
mi6/ic-ui-kit pull request #2336
Opened 2024-08-21 11:57 UTC by gd2910

## Summary of the changes
Change `size` prop 'default' to 'medium'

## Related issue
#2072

2024-08-21 14:04 UTC, GCHQ-Developer-530 requested changes

2024-08-21 14:04 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-data-entity/readme.md
> +# ic-data-entity
This file needs removing, it was replaced by data-list

2024-08-21 14:04 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-select/ic-select.tsx
> +          "full-width": fullWidth,
These changes removing the ic-select- prefix need adding back in

2024-08-27 09:41 UTC, GCHQ-Developer-299 requested changes

2024-08-27 09:41 UTC, GCHQ-Developer-299 commented on packages/react/src/stories/ic-chip.stories.mdx
> +  size: "medium",
I've just looked at Chip and Badge, assume this goes for all playgrounds, but the size control is still showing as small/default/large

<img width="778" alt="Screenshot 2024-08-27 at 10 41 10" src="https://github.com/user-attachments/assets/7f9fd6f7-4425-4f56-83da-6944b2a2af8a">

2024-08-27 11:42 UTC, GCHQ-Developer-299 submitted a review, later dismissed

2024-09-02 07:38 UTC, GCHQ-Developer-299 approved these changes

2024-09-04 12:24 UTC, GCHQ-Developer-530 approved these changes

2024-09-06 08:19 UTC, GCHQ-Developer-530 approved these changes

2024-09-06 13:47 UTC, GCHQ-Developer-299 submitted a review, later dismissed

2024-09-10 13:39 UTC, GCHQ-Developer-299 approved these changes

2024-09-11 07:41 UTC, GCHQ-Developer-530 approved these changes

2024-09-11 07:43 UTC, merged