2091 export data table types
mi6/ic-ui-kit pull request #2401
Opened 2024-09-09 11:32 UTC by GCHQ-Developer-741

## Summary of the changes
- Added export to canary-web-components interface to include missing types relating to data tables. Couldn't add to components.d.ts as they kept getting purged by stencil.
- Added missing return types in ic-data-table that was causing linting errors

## Related issue
#2091 

## Checklist

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [x] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.
- [x] Props/slots can be updated after initial render.

2024-09-10 15:06 UTC, jd239 requested changes
Cheers for looking into this. A few small comments.

2024-09-10 15:09 UTC, jd239 commented
Just tried creating a table with two columns of custom elements and it didn't appear correctly. The example below is using the React slots

```jsx
    <IcDataTable
      caption="Links and Elements in data"
      columns={COLS_ELEMENTS}
      data={DATA_REACT_ELEMENTS}
    >
      {DATA_REACT_ELEMENTS.map((_, index) => (
        <IcButton
          key={index}
          variant="destructive"
          slot={`actions-${index}`}
          onClick={() => console.log("Delete")}
        >
          Delete
        </IcButton>
      ))}
      {DATA_REACT_ELEMENTS.map((_, index) => (
        <IcButton
          key={index}
          variant="tertiary"
          slot={`custom-${index}`}
          onClick={() => console.log("Delete")}
        >
          Delete
        </IcButton>
      ))}
    </IcDataTable>
```

```js
export const COLS_ELEMENTS: IcDataTableColumnObject[] = [
  {
    key: "actions",
    title: "Actions",
    dataType: "element",
    columnAlignment: { horizontal: "center" },
  },
  {
    key: "firstName",
    title: "First name",
    dataType: "string",
  },
  {
    key: "lastName",
    title: "Last name",
    dataType: "string",
  },
  {
    key: "custom",
    title: "Custom",
    dataType: "element",
  },
  {
    key: "age",
    title: "Age",
    dataType: "number",
  },
  {
    key: "jobTitle",
    title: "Job title",
    dataType: "string",
  },
  {
    key: "address",
    title: "Address",
    dataType: "address",
  },
];

```

2024-09-10 15:15 UTC, GCHQ-Developer-741 commented on packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
> +    const organisedSlotData = data.map((row, rowIndex) => {
Will update var name

2024-09-10 15:28 UTC, GCHQ-Developer-741 commented
> Just tried creating a table with two columns of custom elements and it didn't appear correctly. The example below is using the React slots
> 
> ```js
>     <IcDataTable
>       caption="Links and Elements in data"
>       columns={COLS_ELEMENTS}
>       data={DATA_REACT_ELEMENTS}
>     >
>       {DATA_REACT_ELEMENTS.map((_, index) => (
>         <IcButton
>           key={index}
>           variant="destructive"
>           slot={`actions-${index}`}
>           onClick={() => console.log("Delete")}
>         >
>           Delete
>         </IcButton>
>       ))}
>       {DATA_REACT_ELEMENTS.map((_, index) => (
>         <IcButton
>           key={index}
>           variant="tertiary"
>           slot={`custom-${index}`}
>           onClick={() => console.log("Delete")}
>         >
>           Delete
>         </IcButton>
>       ))}
>     </IcDataTable>
> ```
> 
> ```js
> export const COLS_ELEMENTS: IcDataTableColumnObject[] = [
>   {
>     key: "actions",
>     title: "Actions",
>     dataType: "element",
>     columnAlignment: { horizontal: "center" },
>   },
>   {
>     key: "firstName",
>     title: "First name",
>     dataType: "string",
>   },
>   {
>     key: "lastName",
>     title: "Last name",
>     dataType: "string",
>   },
>   {
>     key: "custom",
>     title: "Custom",
>     dataType: "element",
>   },
>   {
>     key: "age",
>     title: "Age",
>     dataType: "number",
>   },
>   {
>     key: "jobTitle",
>     title: "Job title",
>     dataType: "string",
>   },
>   {
>     key: "address",
>     title: "Address",
>     dataType: "address",
>   },
> ];
> ```

I think is due to the fact that when it looks through the columns to see which contain slotted content, it stops once it finds the first one. Will adjust this. Think the whole thing does need an adjustment to add multiple new values to the object rather than one. Cheers for finding this

2024-09-12 11:34 UTC, jd239 approved these changes

2024-09-12 13:15 UTC, GCHQ-Developer-299 approved these changes

2024-09-12 13:55 UTC, merged