fix(web-components): breadcrumb group collapsed prop issue
mi6/ic-ui-kit pull request #2420
Opened 2024-09-12 14:11 UTC by lz405

Fixed the issue with the breadcrumb group collapsed prop not toggling properly and fixed the back arrow not turning back into a chevron

fix #1998 
fix #2028

## Summary of the changes
Fixed the issue where the breadcrumb group prop would, when toggled, not remove the collapsed ellipses element so they would just stack up
Also fixed the issue where, when toggled back and forth, the back arrow for the 'back breadcrumb only' prop would not switch back to a chevron icon

## Related issue
#1998 
#2028

2024-09-13 13:41 UTC, GCHQ-Developer-530 commented
I'm getting some odd behaviour on the collapsed state still, but I think it's a weird edge case. If I toggle in the side panel, it works fine, but when the toggle is set to collapsed="true" and then I click the ellipsis, and set collapsed to "false" in the side panel again, it completely removes breadcrumb 2. It could just be a storybook nuance, but it'd be good if there was a way the playground collapsed value could reflect the actual collapsed value if the ellipsis is clicked e.g. updating the switch to false if the ellipsis is clicked.

https://github.com/user-attachments/assets/eaf8110a-8b6e-447f-9ed4-94da47a84253

2024-10-02 11:34 UTC, gd2910 requested changes
Also getting some strange behaviour in the react storybook where the backBreadcrumbOnly styling is being applied to the current breadcrumb rather than the parent, can't see why this is, may be a SB quirk?

2024-10-02 11:34 UTC, gd2910 commented on packages/react/src/component-tests/IcBreadcrumb/IcBreadcrumb.cy.tsx
> +  it("should switch to the back arrow then back to the chevron", () => {
Please could you alter the test title to be more descriptive, `should switch from default view to back arrow with parent breadcrumb when backBreadcrumbOnly prop is set on IcBreadcrumbGroup and revert when prop is removed`

2024-10-02 11:34 UTC, gd2910 commented on packages/react/src/component-tests/IcBreadcrumb/IcBreadcrumb.cy.tsx
> +    );
Can be removed, not testing anything new

2024-10-28 10:57 UTC, GCHQ-Developer-847 approved these changes

2024-10-29 07:58 UTC, GCHQ-Developer-530 approved these changes

2024-10-29 09:57 UTC, merged