Canary/data table column width functionality
mi6/ic-ui-kit pull request #2423
Opened 2024-09-13 13:29 UTC by jd239

## Summary of the changes
Added functionality which allows consumers to change the column width via the columns array. The value passed from the array updates a `--column-width` CSS property.

## Related issue
#1005 

## Checklist

### General 

- [ ] Changes to docs package checked and committed.
- [ ] All acceptance criteria reviewed and met. 

### Testing

- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [ ] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content.
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] All prop combinations work without issue. 
- [ ] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [ ] Controlled and uncontrolled input components tested.
- [ ] Props/slots can be updated after initial render.

2024-09-20 07:13 UTC, GCHQ-Developer-530 commented on packages/canary-web-components/src/components/ic-data-table/ic-data-table.stories.mdx
> +
Can you add a code example for the sizing story? Same for canary-react as well

2024-09-20 14:34 UTC, GCHQ-Developer-530 submitted a review, later dismissed

2024-09-23 07:34 UTC, ad9242 requested changes

2024-09-23 07:34 UTC, ad9242 commented on packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
> +   * Sets the maximum width of the data table
be good to specify unit supported eg px?, %? etc

2024-09-23 07:34 UTC, ad9242 commented on packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
> +  @Prop() maxWidth?: string;
same re unit

2024-09-23 07:34 UTC, ad9242 commented on packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
> +   * Sets the minimum width of the data table
same re unit

2024-09-23 07:34 UTC, ad9242 commented on packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
> +   * Sets the table width.
same re unit

2024-09-23 07:34 UTC, ad9242 commented on packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
> +   * Sets the table height.
same re unit

2024-09-23 10:24 UTC, GCHQ-Developer-530 approved these changes

2024-09-23 10:31 UTC, GCHQ-Developer-299 approved these changes

2024-09-23 10:37 UTC, ad9242 approved these changes

2024-09-23 10:41 UTC, merged