feat(web-components): add additional functionality to existing ic-divider component
mi6/ic-ui-kit pull request #2526
Opened 2024-10-02 20:17 UTC by GCHQ-Developer-112

## Summary of the changes
Add props to allow existing `ic-divider` to be more customisable, add stories & prop playground, add tests,
update side navigation test following change to ic-divider

BREAKING CHANGE: Change default styling and props on ic-divider

## Related issue
#1331 

## Checklist

### General 

- [ ] Changes to docs package checked and committed.
- [ ] All acceptance criteria reviewed and met. 

### Testing

- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [ ] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content.
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] All prop combinations work without issue. 
- [ ] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [ ] Controlled and uncontrolled input components tested.
- [ ] Props/slots can be updated after initial render.

2024-11-05 19:01 UTC, GCHQ-Developer-847 requested changes
Looks so good! 👏 

Just a couple of small comments

2024-11-06 09:36 UTC, GCHQ-Developer-112 commented on packages/web-components/src/global/color-mode.css
> +  --ic-divider-background: var(--ic-brand-blue-primary);
I think there was a change in the tokens after this work had been done. Fixed it now :)

2024-11-06 10:30 UTC, GCHQ-Developer-847 commented on packages/web-components/src/components/ic-divider/ic-divider.css
> +  * @prop --ic-divider-weight: The thickness of the divider.
Sounds good! I was thinking it kind of conflicts with the `weight` prop i.e. we might not want to allow a completely custom value alongside those options - but yep something to consider in future maybe 👍

2024-11-06 10:41 UTC, GCHQ-Developer-847 approved these changes

2024-11-06 11:11 UTC, GCHQ-Developer-299 approved these changes

2024-11-06 11:12 UTC, merged