ic-card-vertical Dark Mode
mi6/ic-ui-kit pull request #2607
Opened 2024-10-17 08:23 UTC by GCHQ-Developer-741

## Summary of the changes
- Added theme prop to ic-card-vertical, to enable new style tokens for dark mode.
- Added theme prop to tests, storybook and docs

## Related issue
#1214 

## Checklist

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [x] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge).

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.
- [x] Props/slots can be updated after initial render.

2024-10-17 13:09 UTC, ad9242 requested changes
would be good to have at least 1 visual regression test for dark theme. Appreciate there are a lot of combinations\elements, but maybe 1 for now with quite a bit of content, just to give some confidence we don't break anything in future

2024-10-18 12:13 UTC, GCHQ-Developer-741 commented
> would be good to have at least 1 visual regression test for dark theme. Appreciate there are a lot of combinations\elements, but maybe 1 for now with quite a bit of content, just to give some confidence we don't break anything in future

I've implemented 3 visual tests for the dark theme of card, comparing it to light theme and showing the 3 main states of cards. I've included internal elements like the expand button (which is a custom styled button), but other elements that are slotted in like buttons and images I've ignored as they either wont change based on dark theme, or will have their own colour styles and therefore their own visual regression tests.

2024-10-29 17:01 UTC, ad9242 approved these changes

2024-10-29 18:55 UTC, GCHQ-Developer-847 requested changes

2024-10-29 18:55 UTC, GCHQ-Developer-847 commented on packages/web-components/src/global/color-mode.css
> +    --ic-card-vertical-disabled-text: var(--ic-color-text-tertiary);
The disabled text doesn't quite match the designs - I think this should be `var(--ic-color-text-secondary-light)`?

And line 640

2024-10-30 16:33 UTC, GCHQ-Developer-847 approved these changes

2024-11-01 08:01 UTC, ad9242 approved these changes

2024-11-01 09:03 UTC, merged