Tree view fixes
mi6/ic-ui-kit pull request #2621
Opened 2024-10-21 09:12 UTC by GCHQ-Developer-530

## Summary of the changes
Update tree view to not error when no heading is provided. Update tree item to make expanded prop public.

## Related issue
N/A

## Checklist

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [x] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.
- [x] Props/slots can be updated after initial render.

2024-10-21 15:11 UTC, GCHQ-Developer-299 submitted a review, later dismissed

2024-10-24 11:33 UTC, GCHQ-Developer-847 requested changes

2024-10-24 11:33 UTC, GCHQ-Developer-847 commented on packages/canary-web-components/src/components/ic-tree-view/ic-tree-view.stories.mdx
> +An example with expanded prop set to true on a parent tree item.
```suggestion
An example with the `expanded` prop set to `true` on a parent tree item.
```
Also in the React stories

Sorry, I realise I missed this when reviewing the focus inset PR!

2024-10-24 12:18 UTC, GCHQ-Developer-847 approved these changes

2024-10-24 12:22 UTC, GCHQ-Developer-299 approved these changes

2024-10-24 12:25 UTC, merged