2586 ic switch   focus state is not visible in high contrast mode
mi6/ic-ui-kit pull request #2641
Opened 2024-10-24 13:07 UTC by cd3859

## Summary of the changes
Added css for high contrast focus of the ic-switch

## Related issue
#2586 

## Checklist

### General 

- [ ] Changes to docs package checked and committed.
- [ ] All acceptance criteria reviewed and met. 

### Testing

- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [ ] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content.
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] All prop combinations work without issue. 
- [ ] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [ ] Controlled and uncontrolled input components tested.
- [ ] Props/slots can be updated after initial render.

2024-10-24 13:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=2641) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=2641) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=2641) it.</sub>

2024-10-24 14:56 UTC, ad9242 submitted a review, later dismissed

2024-10-24 14:59 UTC, GCHQ-Developer-299 commented on packages/react/cypress-image-diff-screenshots/baseline/IcSwitch.cy.tsx-focus-high-contrast.png
are other focus indicators in HCM this subtle? I'll need to compare.

2024-10-24 15:01 UTC, GCHQ-Developer-299 requested changes
Can you make the focussed state less subtle please?  As a comparison, below is a screenshot of how buttons look when focussed in HCM

<img width="572" alt="Screenshot 2024-10-24 at 16 00 38" src="https://github.com/user-attachments/assets/de49bd8d-cc27-408e-9ebb-a66a5950f59f">

2024-10-24 15:07 UTC, cd3859 commented on packages/react/cypress-image-diff-screenshots/baseline/IcSwitch.cy.tsx-focus-high-contrast.png
I've used the dismissible chips as reference, the issue with a more bold border line is it changes the shape of the switch

2024-10-25 07:27 UTC, ad9242 commented on packages/react/cypress-image-diff-screenshots/baseline/IcSwitch.cy.tsx-focus-high-contrast.png
yeah, I've had a quick look too, but as @cd3859 says, increasing the border size causes movement of the inner content when focus is added\removed, so looks a bit jarring.

2024-10-25 07:30 UTC, MI6-286 commented on packages/react/cypress-image-diff-screenshots/baseline/IcSwitch.cy.tsx-focus-high-contrast.png
On a Quick Look through the VR screenshots we have for focus in HCM, it seems there are a range of thicknesses. Might be worth a wider ticket to look into it.

2024-10-25 07:36 UTC, ad9242 commented on packages/react/cypress-image-diff-screenshots/baseline/IcSwitch.cy.tsx-focus-high-contrast.png
maybe the solution is to go with the "outline" fix you had previously, as that seems to allow you to increase the width, without affecting the inner content. the visual regression base-line will need updating again too - sorry!

2024-10-25 11:10 UTC, cd3859 commented on packages/react/cypress-image-diff-screenshots/baseline/IcSwitch.cy.tsx-focus-high-contrast.png
@GCHQ-Developer-299 added outline similar to checkbox and radio buttons to emphasize focus

2024-10-28 10:32 UTC, GCHQ-Developer-299 approved these changes

2024-10-29 07:41 UTC, GCHQ-Developer-530 approved these changes

2024-10-29 07:42 UTC, merged