Fix/1880 toggle button slots not showing if initially empty
mi6/ic-ui-kit pull request #2708
Opened 2024-11-04 14:53 UTC by lz405

## Summary of the changes
Amend mutation handlers to observe child (slot) elements

## Related issue

fix #1880 

## Checklist

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [x] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.
- [x] Props/slots can be updated after initial render.

2024-11-06 14:39 UTC, GCHQ-Developer-530 approved these changes

2024-11-06 15:24 UTC, GCHQ-Developer-847 approved these changes

2024-11-07 08:29 UTC, ad9242 requested changes
Can we add a disconnectedCallback to ic-toggle-button to remove the mutation observer. Something like this (there is one in ic-button)

disconnectedCallback(): void {
    if (
      this.hostMutationObserver !== null &&
      this.hostMutationObserver !== undefined
    ) {
      this.hostMutationObserver.disconnect();
    }
  }

2024-11-13 13:52 UTC, GCHQ-Developer-530 approved these changes

2024-11-14 07:34 UTC, GCHQ-Developer-530 approved these changes

2024-11-26 14:47 UTC, GCHQ-Developer-847 approved these changes

2024-11-26 14:48 UTC, merged