Pagination theme prop
mi6/ic-ui-kit pull request #2713
Opened 2024-11-05 13:21 UTC by GCHQ-Developer-530

## Summary of the changes
Replace appearance prop with theme and monochrome props on pagination to make use of light and dark
theme colours

BREAKING CHANGE: Appearance prop removed from pagination component and replaced with theme and
monochrome

## Related issue
Working towards #1214 

## Checklist

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [x] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.
- [x] Props/slots can be updated after initial render.

2024-11-05 14:28 UTC, GCHQ-Developer-530 commented
> @GCHQ-Developer-530 I’m a bit curious, why some PRs are against v3 develop and not develop?
> 
> The cherry pick pr only works if you use develop as the commit branch.

Some PRs are only raised against v3 develop as they include breaking changes that we don't want to deploy to the customer yet. The cherry pick PR should take the work that's been done in develop (bug fixes, accessibility errors etc. that we want the customer to have now) and put that in v3 develop so that they're in sync.

2024-11-05 14:39 UTC, evenstensberg commented
Okay, thanks for explaining. The strategy is then to force push the
v3/develop branch when due? I imagine there will be a lot of merge
conflicts, just so you know.


tir. 5. nov. 2024 kl. 15:28 skrev GCHQ-Developer-530 <
***@***.***>:

> @GCHQ-Developer-530 <https://github.com/GCHQ-Developer-530> I’m a bit
> curious, why some PRs are against v3 develop and not develop?
>
> The cherry pick pr only works if you use develop as the commit branch.
>
> Some PRs are only raised against v3 develop as they include breaking
> changes that we don't want to deploy to the customer yet. The cherry pick
> PR should take the work that's been done in develop (bug fixes,
> accessibility errors etc. that we want the customer to have now) and put
> that in v3 develop so that they're in sync.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mi6/ic-ui-kit/pull/2713#issuecomment-2457325578>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD7V5NKRXE366VZCCW7JGMDZ7DIZ3AVCNFSM6AAAAABRGRHAEKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINJXGMZDKNJXHA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-11-06 14:47 UTC, gd2910 submitted a review, later dismissed

2024-11-07 08:36 UTC, ad9242 requested changes
can we update the pagination bar React storybook? I think the Appearance story can be removed and the playground needs the them & monochrome props adding

2024-11-07 08:43 UTC, ad9242 commented on packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx
> +          window.matchMedia("(prefers-color-scheme: dark)").matches)
Would be nice to make the dark mode check a helpers func as it already does similar in ic-theme. But may need to do in both web-components & canary-web-component helpers.ts

2024-11-07 08:49 UTC, ad9242 commented on packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx
> +          window.matchMedia("(prefers-color-scheme: dark)").matches)
actually not required as this code is temporary until ic-button supports theme prop

2024-11-11 10:47 UTC, ad9242 approved these changes

2024-11-11 10:51 UTC, merged