Text field theme
mi6/ic-ui-kit pull request #2741
Opened 2024-11-08 13:07 UTC by GCHQ-Developer-741

## Summary of the changes
- Added dark theme for ic-text-field

## Related issue
#1214 

## Checklist

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [x] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.
- [x] Props/slots can be updated after initial render.

2024-11-11 15:20 UTC, ad9242 commented
is the border for input field in dark theme correct on hover. In figma, it doesn't appear to have a visible border:

![image](https://github.com/user-attachments/assets/a728974a-31d4-48a5-8aaf-9919c9788c59)

but does seem to in storybook:
![image](https://github.com/user-attachments/assets/770730ff-dda4-42ca-96fd-5bdbdfc23789)

2024-11-11 15:40 UTC, GCHQ-Developer-741 commented
> Also, i couldn't see any --ic-text-field tokens added to the color-mode.css file?

My rational behind this is that all the tokens I have utilised to enable dark mode come from either text or atoms, which already have dark mode switching. I thought it unnecessary to duplicate code by repeating dark mode switching, as there each version would be the same:

```css
/* light mode: */
--ic-input-validation-success-icon: var(--ic-atoms-status-icon-success);

/* dark mode: */
--ic-input-validation-success-icon: var(--ic-atoms-status-icon-success);
```

2024-11-12 07:34 UTC, ad9242 requested changes
Please can you add the `theme` prop into the storybook playground?

2024-11-15 11:53 UTC, GCHQ-Developer-299 approved these changes

2024-11-15 14:43 UTC, GCHQ-Developer-299 approved these changes

2024-11-19 10:41 UTC, ad9242 approved these changes

2024-11-19 10:46 UTC, GCHQ-Developer-299 approved these changes

2024-11-19 10:46 UTC, merged