feat(web-components): side-nav tokens
mi6/ic-ui-kit pull request #2786
Opened 2024-11-18 12:54 UTC by gd2910

added color-mode tokens for side-navigation

BREAKING CHANGE: dark mode

2024-11-19 14:50 UTC, GCHQ-Developer-530 requested changes

2024-11-19 14:50 UTC, GCHQ-Developer-530 commented on packages/web-components/src/global/color-mode.css
> +  /* Side navigation  */
Since it's the same tokens for light and dark, these tokens can be moved into colors.css like we've done for classification banner, hero, toast etc.

2024-11-25 07:28 UTC, GCHQ-Developer-530 commented on packages/react/cypress-image-diff-screenshots/baseline/IcSideNavigation.cy.tsx-basic-open.png
It looks like the little divider to the left of the app icon and title has the colour swapped with the lighter blue variant of side nav

2024-11-27 10:24 UTC, GCHQ-Developer-741 commented on packages/web-components/src/global/color-mode.css
> +  /* Side navigation  */
If these have been moved to colors.css, do they still need to be in this file? None of the others like this (Toast, Hero, etc.) are in here.

2024-11-27 15:00 UTC, ad9242 submitted a review, later dismissed

2024-11-27 15:05 UTC, GCHQ-Developer-741 approved these changes

2024-11-28 12:52 UTC, GCHQ-Developer-847 approved these changes

2024-11-28 13:34 UTC, merged