fix(web-components): fix side navigation 'failed to execute getComputedStyle' console error
mi6/ic-ui-kit pull request #2802
Opened 2024-11-20 10:25 UTC by lz405

## Summary of the changes
added null handling if there is no icon for navigation item

## Related issue
fix #2795 

## Checklist

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [x] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.
- [x] Props/slots can be updated after initial render.

2024-11-20 13:44 UTC, evenstensberg commented on packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx
> +      iconWidth: navItemSVG ? window.getComputedStyle(navItemSVG).width : "0",
Maybe add an optional chaining to the method object and add it to the rest of the methods that call the same function? 

Best would be to add the check to the function itself. This way you guarantee any calls to the function will return something anywhere

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2024-11-20 14:00 UTC, evenstensberg commented on packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx
> +      iconWidth: navItemSVG ? window.getComputedStyle(navItemSVG).width : "0",
```suggestion
      iconWidth: navItemSVG ? window.getComputedStyle(navItemSVG)?.width : "0",
```

2024-11-25 09:46 UTC, GCHQ-Developer-299 requested changes
While clicking rapidly between React sidenav stories (how i've made the error occur before) I found that style errors do still occur sometimes in another method - screenshot attached:
<img width="1151" alt="Screenshot 2024-11-25 at 09 45 27" src="https://github.com/user-attachments/assets/fc1c803a-5153-4952-92a1-cbd146581831">

2024-11-25 10:48 UTC, evenstensberg commented
@GCHQ-Developer-299 Thats why you should either use optional changing and ternaries, or null-ish coacending in all your util methods.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

2024-11-28 11:34 UTC, GCHQ-Developer-299 approved these changes

2024-12-02 13:02 UTC, gd2910 commented
LGTM

2024-12-03 11:52 UTC, merged