fix(web-components): ic-alert change
mi6/ic-ui-kit pull request #2854
Opened 2024-12-03 10:09 UTC by gd2910

## Summary of the changes
Capitalised tooltip

2024-12-03 10:11 UTC, GCHQ-Developer-112 approved these changes

2024-12-03 10:54 UTC, GCHQ-Developer-299 approved these changes

2024-12-03 10:56 UTC, GCHQ-Developer-299 requested changes
please update unit test snapshots

2024-12-03 17:11 UTC, GCHQ-Developer-847 approved these changes

2024-12-04 08:29 UTC, GCHQ-Developer-530 approved these changes

2024-12-04 08:39 UTC, GCHQ-Developer-299 approved these changes

2024-12-04 08:40 UTC, merged