1960 ic text field autofocus prop not working unless text field label is hidden
mi6/ic-ui-kit pull request #2901
Opened 2024-12-13 15:11 UTC by gd2910

## Summary of the changes
`autofocus` was only being applied when the label was hidden, this was due to the child components rendering after the `ic-text-field` components.

Changes;
- `setInterval` waits until typography is hydrated before setting focus on input
- `autofocus` renamed from `auto-focus` to align more closely with native attribute

## Related issue
#1960

2024-12-31 10:51 UTC, ad9242 requested changes

2024-12-31 10:51 UTC, ad9242 commented on packages/web-components/src/components/ic-text-field/ic-text-field.tsx
> +                name={this.name}
is this change needed? isn't name already accessible from the object restructuring in the render method (line 474)?

2025-01-02 11:56 UTC, GCHQ-Developer-847 requested changes
I think it would be worth updating the info about the breaking changes in the commit messages to be even clearer about what the change actually is

2025-01-06 11:37 UTC, GCHQ-Developer-847 approved these changes

2025-01-07 14:14 UTC, ad9242 approved these changes

2025-01-07 14:14 UTC, merged