Removed `disabled` attribute from all components when set to false
mi6/ic-ui-kit pull request #2930
Opened 2024-12-18 12:49 UTC by GCHQ-Developer-741

## Summary of the changes
Following changes to certain components to ensure the disabled attribute is fully removed from the component, replicated across all components that have a disabled attribute to ensure consistency and correct behaviour with screen readers.

## Related issue
#2629 

## Checklist

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [x] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge).

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.
- [x] Props/slots can be updated after initial render.

2024-12-20 11:19 UTC, ad9242 commented
looks good, but do you think it would be good to add unit tests that specifically set it to `disabled=false`, so we can check that it's actually removing it from the element (by comparing with dom snapshot)

2024-12-31 13:47 UTC, ad9242 requested changes
see comment re adding unit tests

2025-01-02 10:49 UTC, GCHQ-Developer-741 commented
Have added the unit tests (except for the ic-data-input/picker because I couldn't get the snapshots generated)

2025-01-02 12:46 UTC, GCHQ-Developer-847 requested changes
I think the select is missing a watch on its `disabled` prop and a unit test, but all looks good apart from that

I don't have NVDA so can't test with that, but since this solution was already working on some components, I assume it's ok - so will be happy to approve once the above issue is resolved :)

2025-01-02 14:29 UTC, GCHQ-Developer-847 approved these changes

2025-01-06 11:32 UTC, GCHQ-Developer-299 approved these changes
Tested on the Accordion and Select Playground stories - by toggling on/off 'disabled'. On Develop, the accordion would still read as 'unavailable' after it was undisabled, on your branch it correctly did not :)

2025-01-06 13:24 UTC, ad9242 approved these changes

2025-01-06 16:28 UTC, merged