2064 codemod for v2 to v3
mi6/ic-ui-kit pull request #2947
Opened 2024-12-19 18:27 UTC by cd3859

## Summary of the changes
codemod to help convert files to new v3 props and component names

notes: 
 - Testing file is specific for testing apps way of testing, may require further generalisation to work with other projects

## Related issue
#2064

2025-01-07 11:30 UTC, GCHQ-Developer-847 requested changes
I guess the actual functionality will be checked properly as part of [#33](https://github.com/mi6/ic-ui-kit-test-app/issues/33) - but I have spotted a few things while looking through the code :)

2025-01-07 11:30 UTC, GCHQ-Developer-847 commented on packages/codemod/README.md
Please have a look at how this file is being displayed in the [preview markdown](https://github.com/mi6/ic-ui-kit/blob/396cda8bdd0a8653511bcf9913f34866b53bb1a0/packages/codemod/README.md) :)

Some aspects could maybe be a bit clearer / more readable e.g. lines 11-14 are being displayed in one line, and the "\<dir\>" and "\<type\>" on line 7 aren't visible

2025-01-07 11:30 UTC, GCHQ-Developer-847 commented on packages/codemod/changeReact.json
> +      "v3Name": "size={small}",
Is it correct to use curly braces? I would've thought it would be passed in as a string, e.g.`size='small'`

2025-01-07 11:30 UTC, GCHQ-Developer-847 commented on packages/codemod/changes.json
> +    "v2Name": "size=default",
Not sure if these will need quotes as they are strings? E.g. `size='default'`

2025-01-07 11:30 UTC, GCHQ-Developer-847 commented on packages/codemod/README.md
> +  --dir      directory to components using icds
I think this could be a bit clearer - maybe this?:
```suggestion
  --dir      directory containing ICDS components
```

2025-01-07 12:38 UTC, gd2910 commented on packages/codemod/changeReact.json
> +      "v3Name": "IcVerticalCard",
```suggestion
      "v3Name": "IcCardVertical",
```

2025-01-07 12:39 UTC, gd2910 commented
I've had some IcSelect props come through incorrectly while testing;

![image](https://github.com/user-attachments/assets/683ac97a-de2e-42d6-8201-306b9af59e4d)

2025-01-07 12:42 UTC, gd2910 commented
In V3 `IcSelectWithMulti` is now incorporated into 'IcSelect` with the `multiple` attribute.

2025-01-07 14:04 UTC, gd2910 commented
Can we use Codemod to replace the types also?

ie;
![image](https://github.com/user-attachments/assets/7e97a91d-cf93-4840-a9f2-cbc05a738dcb)

2025-01-07 14:07 UTC, gd2910 commented
There are places where the prop is accessed with the V2, although I don't think we can support or expect the codemod to change this, as we've no access to what the component is stored as in the test and it may inadvertently break other parts of an app.

![image](https://github.com/user-attachments/assets/99de60af-9c56-4599-b379-20342182acfa)

2025-01-08 13:45 UTC, gd2910 commented
Tested locally on the [ic-ui-kit-test-app](https://github.com/mi6/ic-ui-kit-test-app) in this [PR](https://github.com/mi6/ic-ui-kit-test-app/pull/34). Happy to tick once comments addressed.

2025-01-09 19:10 UTC, evenstensberg reviewed
A few thought on what could be improved. Dismiss this review if you're not ready for these adjustments yet.

2025-01-09 19:10 UTC, evenstensberg commented on packages/codemod/codemod.js
> +    console.error("Error reading file:", err);
A logger library that prettifies console logs would be nice to include.


https://blog.logrocket.com/best-node-js-logging-libraries-aggregators/

2025-01-09 19:10 UTC, evenstensberg commented on packages/codemod/codemod.js
> +main(directoryPath, changeType);
main is defined as an async function but the await keyword isn't invoked in global scope.

2025-01-09 19:10 UTC, evenstensberg commented on packages/codemod/codemod.js
> +const directoryPath = process.argv[2];
https://yargs.js.org/ 

can make the CLI ui better for your users. If you decide not to implement a logging library (see previous pr comments), style the output a bit.

(https://www.npmjs.com/package/chalk)

2025-01-09 19:10 UTC, evenstensberg commented on packages/codemod/codemod.js
> +  process.exit(1);
```suggestion
  process.exitCode = 1;
  return;
```

2025-01-09 19:10 UTC, evenstensberg commented on packages/codemod/package.json
> +    "description": "Codemod to upgrade v2 to v3",
needs more information

2025-01-09 19:10 UTC, evenstensberg commented on packages/codemod/sections/directory-search.js
> +    //console.log(`Reading directory: ${directoryPath}`);
remove unused logs

2025-01-09 19:10 UTC, evenstensberg commented on packages/codemod/sections/simple-test-comparison.js
> +    jsonData.map((entry) => {
inline this 

```js
arr.map(obj => obj.v2name))
```

2025-01-09 19:10 UTC, evenstensberg commented on packages/codemod/sections/test-comparison.js
> +        if (match !== null) {
You can use early return here to decouple some indentation levels.

2025-01-09 19:10 UTC, evenstensberg commented on packages/codemod/sections/test-comparison.js
> +  //return the new file string
remove

2025-01-10 15:23 UTC, gd2910 commented on packages/codemod/codemod.js
> +    console.error("Error reading file:", err);
Thanks for the suggestion, I have raised a separate [ticket](https://github.com/mi6/ic-ui-kit/issues/3003) for the team to discuss this. For now this PR is key to our release schedule, so feature improvements will likely be made after merge.

2025-01-10 15:23 UTC, gd2910 commented on packages/codemod/codemod.js
> +const directoryPath = process.argv[2];
As above

2025-01-14 10:36 UTC, evenstensberg commented
@cd3859 could you add yargs (see previous comment)? It will improve developer experience and is only 3-4 lines of code.

2025-01-14 16:09 UTC, evenstensberg commented on packages/codemod/codemod.js
> +const directoryPath = process.argv[2];
I’ll rebase my pr once this is ready for review

2025-01-14 16:10 UTC, cd3859 commented on packages/codemod/sections/test-comparison.js
> +        if (match !== null) {
Going to leave this as is right now as it's unused but will either be refactored or removed later down the line

2025-01-15 12:58 UTC, evenstensberg commented
See #3032

2025-01-16 09:10 UTC, gd2910 approved these changes

2025-01-16 12:07 UTC, GCHQ-Developer-847 requested changes
I think the code for the functionality looks good to me now, and I'm happy that [the PR on the ic-ui-kit test app](https://github.com/mi6/ic-ui-kit-test-app/pull/34) demonstrates that it works.

I have just noticed a few more small things in the README. Sorry, I think I missed them last time I reviewed!

2025-01-16 13:07 UTC, GCHQ-Developer-847 approved these changes

2025-01-16 14:14 UTC, evenstensberg commented
@cd3859 if you want, #3038 is a good addition to a good experience using the codemod. Not required but it’s nice.

2025-01-16 14:25 UTC, gd2910 requested changes
Waiting on updated json files, will approve after TODO

2025-01-20 11:56 UTC, GCHQ-Developer-847 approved these changes

2025-01-20 11:58 UTC, merged