Add react types to fix build issue
mi6/ic-ui-kit pull request #2956
Opened 2024-12-23 14:45 UTC by dn55533

## Summary of the changes
Fixed build problem in web-components by adding dependency on React types.

The npm run build task was failing with the following error: Cannot find namespace 'JSX'

This has been fixed by adding dev dependencies on the following React types:

- @types/react
- @types/react-dom

## Related issue
N/A

## Checklist

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [x] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.
- [x] Props/slots can be updated after initial render.

2024-12-30 10:15 UTC, ad9242 commented
It shouldn't need React specific packages adding at the root level. If anywhere, we'd expect them to be needed in react & canary-react packages (in theory only for running storybook or the cypress tests, where the react components are used)

What was the reason for adding them at this level? Doing the following in the root folder 
```
npm install
npm run bootstrap
npm run build
```

does not seem to cause any issues, so it would be good to get to the bottom of if this is something environmental before adding additional dependencies for everyone to the root level

Also, if they were to be added, ideally they would not need to be locked to a specific version and could be locked to a minimum version as with all other dependencies

2024-12-30 12:17 UTC, dn55533 commented
WIthout these dependencies, the project fails to build using those three commands. I tried multiple times, including cloning the repo from scratch into a new folder.

When I added those dependencies, it fixed the problem.

I'm not sure where the best place to put these dependencies, so I went with the root level. Happy to move them if needed.

2024-12-30 16:55 UTC, ad9242 commented
Interestingly, where it shows the error, it seems to be using Stencil version 4.23.0
@ukic/web-components: [40:28.3] @stencil/core
@ukic/web-components: [40:29.0] v4.23.0 
@ukic/web-components: [40:34.2] build, core, prod mode, started ...

When we follow the steps you mention, it installs Stencil v4.10.0 as set in the [package-lock.json](https://github.com/mi6/ic-ui-kit/blob/dee234161a67a9b42a20f4bc385a05da65b2cf4d/packages/web-components/package-lock.json#L4996)

Do you know of anything in your setup that could be causing the newer version of Stencil to be installed, as we are struggling to recreate this?

2025-01-02 10:40 UTC, MI6-255 requested changes
Currently waiting on a discussion internally, marking as requested changes to prevent a merge.

2025-01-06 10:22 UTC, GCHQ-Developer-112 commented
> Hi @dn55533, I've been able to recreate the issue you were facing. Please can you install the two types packages at version 17 so they match the versions of the `react` and `react-dom` dev dependencies that are already installed. Please can you also do the install in the `web-components` folder instead of the root folder

One more thing, please refer to our [CONTRIBUTING.md](https://github.com/mi6/ic-ui-kit/blob/main/CONTRIBUTING.md#git-commit) for guidance on how to format your commit

2025-01-07 09:31 UTC, GCHQ-Developer-112 approved these changes

2025-01-07 10:02 UTC, GCHQ-Developer-112 requested changes
Please also commit the updated `package-lock.json` in the `web-components` folder

2025-01-08 08:54 UTC, GCHQ-Developer-112 approved these changes

2025-01-08 08:59 UTC, merged