Add onclick to action element
mi6/ic-ui-kit pull request #2957
Opened 2024-12-27 16:13 UTC by am26090

## Summary of the changes
In the data table on the data prop, where the action element is added, i have added an on click to the actionElement, with a ternary to only use click when a prop is passed.

## Related issue
2943

## Checklist

### General 

- [ ] Changes to docs package checked and committed.
- [ ] All acceptance criteria reviewed and met. 

### Testing

- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [ ] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content.
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] All prop combinations work without issue. 
- [ ] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [ ] Controlled and uncontrolled input components tested.
- [ ] Props/slots can be updated after initial render.

2024-12-30 10:03 UTC, MI6-255 commented
Thanks for your contribution, you just need to run prettier to fix the broken GitHub checks.

2024-12-30 11:44 UTC, am26090 commented
> Thanks for your contribution, you just need to run prettier to fix the broken GitHub checks, then a member of the team will take a look.

Should be done

2024-12-30 16:28 UTC, ad9242 requested changes
It would be good to add some documentation about the actionElement and actionOnClick. This would make it much clearer for users as at the moment you have to look into the code or examples to discover that this functionality exists.

Maybe as a new story, after the "Links and Elements in data" story (ideally in both canary-web-components & canary-react) along with a paragraph describing the functionality (and maybe why users might want to go with this approach rather than using slotted elements)

2024-12-31 10:16 UTC, ad9242 requested changes
Please can you also add the sample code to the canary-web-components Action Element story (like other stories above it in the file)?

2024-12-31 10:16 UTC, ad9242 commented on packages/canary-react/src/stories/ic-data-table.stories.mdx
> +      actionOnClick: () => console.log('hello)
```suggestion
      actionOnClick: () => console.log('hello')
```

2025-01-07 08:20 UTC, ad9242 requested changes
Please can you run `npm run prettier:fix` and commit the changes?

Also please check that the Cypress tests are running\passing locally, as they seem to be failing in the CI (none of the data-table tests are running, due to an error in the file it seems.

Please can you also squash the commits? There should be only 1 commit at each scope: "feat(canary-web-components)........" (note "s" on end) and "feat(canary-react) .......". So this Pull Request would then only contain 2 commits.

2025-01-07 17:26 UTC, am26090 commented
> Please can you run `npm run prettier:fix` and commit the changes?
> 
> Also please check that the Cypress tests are running\passing locally, as they seem to be failing in the CI (none of the data-table tests are running, due to an error in the file it seems.
> 
> Please can you also squash the commits? There should be only 1 commit at each scope: "feat(canary-web-components)........" (note "s" on end) and "feat(canary-react) .......". So this Pull Request would then only contain 2 commits.

ive tried to get it down to 2 commits, goes wrong every time. So ive got it to 3, if thats ok

2025-01-08 08:06 UTC, ad9242 commented
I think we will need to get that commit removed I'm afraid. One option would be to create a new branch off the latest develop & then cherry-pick your other commits:

eg
```
git cherry-pick bfa8d62942887272d5c9f0be51d3f7752c94b907
git cherry-pick 702d9fc62d0578778626287e463ed3518d82469b
```
and then create a new PR for that branch

it looks like this also needs a `npm run:prettier:fix` too to resolve some formatting issues

2025-01-08 10:44 UTC, am26090 commented
> I think we will need to get that commit removed I'm afraid. One option would be to create a new branch off the latest develop & then cherry-pick your other commits:
> 
> eg
> 
> ```
> git cherry-pick bfa8d62942887272d5c9f0be51d3f7752c94b907
> git cherry-pick 702d9fc62d0578778626287e463ed3518d82469b
> ```
> 
> and then create a new PR for that branch
> 
> it looks like this also needs a `npm run:prettier:fix` too to resolve some formatting issues

new pr, see here https://github.com/mi6/ic-ui-kit/pull/2986/commits

2025-01-08 10:44 UTC, closed without merging