ic-status-tag - Added Prop which conditionally makes the comp an aria-live region
mi6/ic-ui-kit pull request #300
Opened 2023-01-18 11:55 UTC by gd2910

## Summary of the changes
The announced tag adds the role='status' prop and adds the aria-live status, more explicit aria-label descriptors added to span element. A11y tests changed to reflect and unit tests added for new prop.

## Related issue
#20  

## Checklist
- [ ] I have added relevant unit and visual regression tests.
- [ ] I have manually accessibility tested any changes, if relevant.
- [ ] I have ensured any changes match the Figma component library.

2023-01-18 11:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=300) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=300) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: jd239<br/>:x: gd2910<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=300) it.</sub>

2023-01-18 14:02 UTC, GCHQ-Developer-530 reviewed
Think the branch just needs to rebase off develop to get rid of the other 5 commits, but looks good other than that :)

2023-01-18 15:08 UTC, ad9242 commented on packages/web-components/src/components/ic-status-tag/ic-status-tag.tsx
> +   * If 'true' the component will act as an 'aria-live' region.
```suggestion
   * If 'true', the component will act as an 'aria-live' region.
```

2023-01-18 15:09 UTC, ad9242 requested changes
minor typo, but looks good otherwise

2023-01-19 07:38 UTC, GCHQ-Developer-530 submitted a review, later dismissed

2023-01-24 10:54 UTC, gd2910 commented
PR closed due to git issues, please see new status-tag PR

2023-01-24 10:54 UTC, closed without merging