Announced prop added to ic-status-tag
mi6/ic-ui-kit pull request #313
Opened 2023-01-24 11:02 UTC by gd2910

The status tag had a role property that was not being read out by assistive technology.

## Summary of the changes
Added an 'Announced' prop that conditionally renders the status-tag component as an aria-live region. This is a fix for the aria-label being read out incorrectly. This is set as 'false' by default. 

When set as 'true' the status-tag will act as an aria-live region.

## Related issue
Connected ticket: https://github.com/mi6/ic-ui-kit/issues/20

This is an updated PR from a now deleted previous PR/branch

## Checklist
- [ ] I have added relevant unit and visual regression tests.
- [ ] I have manually accessibility tested any changes, if relevant.
- [ ] I have ensured any changes match the Figma component library.

2023-01-25 16:41 UTC, jd239 requested changes
Two minor comments. 👍

2023-01-25 16:41 UTC, jd239 commented on packages/web-components/src/components/ic-status-tag/ic-status-tag.tsx
> +   * If 'true', the component will act as an 'aria-live' region.
Is it worth mentioning it adds the `role=status` to the component as I was initially confused why it talks about aria-live?

2023-01-25 16:41 UTC, jd239 commented on packages/web-components/src/components/ic-status-tag/ic-status-tag.tsx
> +        aria-label={"Status. " + `${label}`}
This can be done as
```jsx
aria-label={`Status. ${label}`}
```

2023-01-26 17:06 UTC, GCHQ-Developer-847 requested changes
Just noticed a couple of tiny things

2023-01-26 17:15 UTC, jd239 commented on packages/web-components/src/components/ic-status-tag/readme.md
> +| `announced`          | `announced`  | If 'true', the component will act as an 'aria-live' region.     | `boolean`                                         | `false`     |
Think you need to run the build again to update this readme file. `npm run build`

2023-01-27 10:26 UTC, jd239 approved these changes

2023-01-27 12:04 UTC, GCHQ-Developer-847 approved these changes

2023-01-30 10:03 UTC, jd239 approved these changes

2023-01-30 10:19 UTC, merged