Fix for long single-word app titles in top-navigation
mi6/ic-ui-kit pull request #314
Opened 2023-01-24 11:33 UTC by gd2910

Fixed a bug where a long single-word app title would push other elements such as 'search' and 'chips' outside of the browser window.

## Summary of the changes
Class added to app title that enables wrap for longer titles

## Related issue
Ticket: https://github.com/mi6/ic-ui-kit/issues/175

## Checklist
- [ ] I have added relevant unit and visual regression tests.
- [ ] I have manually accessibility tested any changes, if relevant.
- [ ] I have ensured any changes match the Figma component library.

2023-01-24 13:30 UTC, GCHQ-Developer-847 requested changes
Looks great! Just a couple of things from me

2023-01-24 13:30 UTC, GCHQ-Developer-847 commented on packages/web-components/src/components/ic-top-navigation/ic-top-navigation.stories.mdx
> +### Long single-word app title
I think we want this same story adding to the React storybook as well (react/src/stories)

2023-01-24 13:30 UTC, GCHQ-Developer-847 commented on packages/web-components/src/components/ic-top-navigation/ic-top-navigation.stories.mdx
> +import { Meta, Story, Canvas, ArgsTable, Description } from '@storybook/addon-docs';
Looks like some of the formatting in this file has changed - running 'npm run prettier:fix' should fix it 🙂

2023-01-24 16:29 UTC, GCHQ-Developer-847 approved these changes

2023-01-24 16:41 UTC, ad9242 approved these changes

2023-01-25 10:58 UTC, DBD324 requested changes
When trying different combinations of titles in the new version I seem to still get some strange hyphenation behaviour. On the image below I used a title of some long words and some short ones. Oddly, the first word that wraps onto three lines doesn't use a hyphen between line 1 and 2, but does between line 2 and 3. 

![image](https://user-images.githubusercontent.com/116820773/214545794-2df72055-1cff-4920-8a39-43bf0817d476.png)

2023-01-25 13:19 UTC, ad9242 commented
> When trying different combinations of titles in the new version I seem to still get some strange hyphenation behaviour. On the image below I used a title of some long words and some short ones. Oddly, the first word that wraps onto three lines doesn't use a hyphen between line 1 and 2, but does between line 2 and 3.
> 
> ![image](https://user-images.githubusercontent.com/116820773/214545794-2df72055-1cff-4920-8a39-43bf0817d476.png)

I think it might be a quirk of the browser. I just tried outside of the component with different text and get this behaviour: 
![image](https://user-images.githubusercontent.com/116102637/214573354-f4ee9354-aab7-403e-98c8-ee580ee94bf8.png)

2023-01-30 11:45 UTC, DBD324 commented
Is there a method to truncate instead of wrap? Worried about the effect of long title on small screen devices where the wrapping would push the page content down the page. Truncation and tooltip may be a handy solution here for pointer users.

2023-01-30 12:11 UTC, DBD324 approved these changes
Thanks for exploring the wrapping and hyphenation behavior. Looks good.

2023-01-30 14:16 UTC, merged