*new* 'Latest announcement' box in ic-hero on xs breakpoint bug
mi6/ic-ui-kit pull request #358
Opened 2023-02-07 15:47 UTC by gd2910

## Summary of the changes
On XS devices the bottom of the secondary slot was touching the section-container.

Padding has been added to the XS breakpoint on section-container

This has been manually tested by creating a storybook component and re-sizing the screen.

Story removed as it didn't add value/show new feature
## Related issue
#302 

## Checklist
- [ ] I have added relevant unit and visual regression tests.
- [ ] I have manually accessibility tested any changes, if relevant.
- [ ] I have ensured any changes match the Figma component library.

2023-02-07 15:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=358) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=358) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: gd2910<br/>:x: github-actions[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=358) it.</sub>

2023-02-10 09:42 UTC, GCHQ-Developer-530 approved these changes

2023-02-10 10:06 UTC, jd239 commented on packages/web-components/src/components/ic-hero/ic-hero.css
> +    margin-bottom: 1rem;
Can you swap the value for our design token: https://github.com/mi6/ic-ui-kit/blob/main/packages/web-components/src/global/variables.css#L276

2023-02-10 10:07 UTC, jd239 requested changes
Tiny update for the CSS file to use our design token

2023-02-10 11:06 UTC, GCHQ-Developer-530 approved these changes

2023-02-10 12:43 UTC, jd239 approved these changes

2023-02-10 12:44 UTC, merged