fix(web-components): fixed flickering link hovering
mi6/ic-ui-kit pull request #389
Opened 2023-02-17 10:52 UTC by GCHQ-Developer-741

Removed unecessary hc outline that was causing flickering when the link is focused

## Checklist
- [x] I have added relevant unit and visual regression tests.
- [x] I have manually accessibility tested any changes, if relevant.
- [x] I have ensured any changes match the Figma component library.

2023-02-17 11:24 UTC, GCHQ-Developer-530 approved these changes

2023-02-17 14:21 UTC, GCHQ-Developer-847 submitted a review, later dismissed

2023-02-17 14:51 UTC, MI6-255 requested changes

2023-02-17 14:51 UTC, MI6-255 commented on audit-ci.json
> +    "GHSA-c2jc-4fpr-4vhg"
Anything we can upgrade to prevent needing to add this?

2023-02-20 14:33 UTC, MI6-255 approved these changes

2023-02-20 16:24 UTC, merged