fix(web-components): add extra values for underline thickness and offset for safari to use
mi6/ic-ui-kit pull request #511
Opened 2023-03-23 14:10 UTC by GCHQ-Developer-530

## Summary of the changes
As safari doesn't support percentage values for text-decoration-thickness or text-underline-offset, these values have been duplicated but using rem values instead for card, breadcrumb, link and footer link, so that safari will pick them up.

## Related issue
#508 

## Checklist
- [x] I have added relevant unit and visual regression tests.
- [x] I have manually accessibility tested any changes, if relevant.
- [x] I have ensured any changes match the Figma component library.

2023-03-23 16:17 UTC, jd239 commented
Had a look at this on Safari 16.3. The offset works but the thickness doesn't on breadcrumbs. However, it does on IcLink but the idle state of the link is displaying two instead of one after the initial hover.

2023-03-27 08:45 UTC, GCHQ-Developer-112 requested changes
The hover state now works on Safari but it doesn't behave as expected. On hover, the underline moves down as expected, however on release of the hover, both the text and line move. The expected behaviour is that the line moves back to its original position and is no longer bold, as opposed to both the line and text moving.

2023-03-27 11:45 UTC, MI6-255 submitted a review, later dismissed

2023-03-27 11:51 UTC, GCHQ-Developer-112 commented
Hey, just had another look at the build and found a few bugs:
**1. The icons is also being underlined for the breadcrumbs component** 
    <img width="174" alt="Screenshot 2023-03-27 at 12 26 08" src="https://user-images.githubusercontent.com/113986285/227929672-75afe3ac-0b70-4a3b-b538-0e552467e9b2.png">
   <img width="160" alt="Screenshot 2023-03-27 at 12 26 17" src="https://user-images.githubusercontent.com/113986285/227929674-0659fc90-c10d-4182-81db-94b52e626cce.png">

**2. Small issue but the underline under the ellipsis (...) extends past the ellipsis, which it didn't before** 
    <img width="49" alt="Screenshot 2023-03-27 at 12 26 47" src="https://user-images.githubusercontent.com/113986285/227929677-0b4b644d-10f4-4318-a19e-a71cec9eae56.png">

**3. The thickness of the underline in the cards looks slightly off**
    Now (as seen in this PR): 
    <img width="534" alt="Screenshot 2023-03-27 at 12 28 01" src="https://user-images.githubusercontent.com/113986285/227929679-3fc114de-8332-4f14-8ff8-eed7d56a919c.png">

   Previously (as seen in `develop`):
   <img width="533" alt="Screenshot 2023-03-27 at 12 28 07" src="https://user-images.githubusercontent.com/113986285/227929684-2a66f5d1-e06d-45e9-b071-c8191c751f5f.png">

**4. The underline under the footer links doesn't seem to be offset as much as the other links** 
    Now (as seen in this PR): 
    <img width="109" alt="Screenshot 2023-03-27 at 12 30 41" src="https://user-images.githubusercontent.com/113986285/227929686-6506ca9d-c411-4ebd-8e9f-d34c3a092c0b.png">

   Previously (as seen in `develop`):
    <img width="108" alt="Screenshot 2023-03-27 at 12 30 48" src="https://user-images.githubusercontent.com/113986285/227929689-923bb7f3-228f-4dde-8d5b-132980538f4d.png">

**5. The icons are now being underlined**
    <img width="82" alt="Screenshot 2023-03-27 at 12 31 25" src="https://user-images.githubusercontent.com/113986285/227929692-049f2f7d-1890-47ea-94a2-bf538b83542a.png">

2023-03-27 12:08 UTC, GCHQ-Developer-530 commented
> Hey, just had another look at the build and found a few bugs: **1. The icons is also being underlined for the breadcrumbs component** <img alt="Screenshot 2023-03-27 at 12 26 08" width="174" src="https://user-images.githubusercontent.com/113986285/227929672-75afe3ac-0b70-4a3b-b538-0e552467e9b2.png"> <img alt="Screenshot 2023-03-27 at 12 26 17" width="160" src="https://user-images.githubusercontent.com/113986285/227929674-0659fc90-c10d-4182-81db-94b52e626cce.png">
> 
> **2. Small issue but the underline under the ellipsis (...) extends past the ellipsis, which it didn't before** <img alt="Screenshot 2023-03-27 at 12 26 47" width="49" src="https://user-images.githubusercontent.com/113986285/227929677-0b4b644d-10f4-4318-a19e-a71cec9eae56.png">
> 
> **3. The thickness of the underline in the cards looks slightly off** Now (as seen in this PR): <img alt="Screenshot 2023-03-27 at 12 28 01" width="534" src="https://user-images.githubusercontent.com/113986285/227929679-3fc114de-8332-4f14-8ff8-eed7d56a919c.png">
> 
> Previously (as seen in `develop`): <img alt="Screenshot 2023-03-27 at 12 28 07" width="533" src="https://user-images.githubusercontent.com/113986285/227929684-2a66f5d1-e06d-45e9-b071-c8191c751f5f.png">
> 
> **4. The underline under the footer links doesn't seem to be offset as much as the other links** Now (as seen in this PR): <img alt="Screenshot 2023-03-27 at 12 30 41" width="109" src="https://user-images.githubusercontent.com/113986285/227929686-6506ca9d-c411-4ebd-8e9f-d34c3a092c0b.png">
> 
> Previously (as seen in `develop`): <img alt="Screenshot 2023-03-27 at 12 30 48" width="108" src="https://user-images.githubusercontent.com/113986285/227929689-923bb7f3-228f-4dde-8d5b-132980538f4d.png">
> 
> **5. The icons are now being underlined** <img alt="Screenshot 2023-03-27 at 12 31 25" width="82" src="https://user-images.githubusercontent.com/113986285/227929692-049f2f7d-1890-47ea-94a2-bf538b83542a.png">

Now that we discovered that text-decoration-thickness and text-underline-offset aren't having any effect in safari, there seems to be no other way to restrict the underline to just the text within a link, so it's underlining the icons and extending the line on the ellipsis etc. So I'm not too sure of a fix for these issues, it may be worth a bigger team discussion about whether we just wait for percentage values for text-decoration-thickness and text-underline-offset to be compatible with safari as it seems to work for most other browsers.

2023-03-27 12:39 UTC, MI6-255 commented
> > Hey, just had another look at the build and found a few bugs: **1. The icons is also being underlined for the breadcrumbs component** <img alt="Screenshot 2023-03-27 at 12 26 08" width="174" src="https://user-images.githubusercontent.com/113986285/227929672-75afe3ac-0b70-4a3b-b538-0e552467e9b2.png"> <img alt="Screenshot 2023-03-27 at 12 26 17" width="160" src="https://user-images.githubusercontent.com/113986285/227929674-0659fc90-c10d-4182-81db-94b52e626cce.png">
> > **2. Small issue but the underline under the ellipsis (...) extends past the ellipsis, which it didn't before** <img alt="Screenshot 2023-03-27 at 12 26 47" width="49" src="https://user-images.githubusercontent.com/113986285/227929677-0b4b644d-10f4-4318-a19e-a71cec9eae56.png">
> > **3. The thickness of the underline in the cards looks slightly off** Now (as seen in this PR): <img alt="Screenshot 2023-03-27 at 12 28 01" width="534" src="https://user-images.githubusercontent.com/113986285/227929679-3fc114de-8332-4f14-8ff8-eed7d56a919c.png">
> > Previously (as seen in `develop`): <img alt="Screenshot 2023-03-27 at 12 28 07" width="533" src="https://user-images.githubusercontent.com/113986285/227929684-2a66f5d1-e06d-45e9-b071-c8191c751f5f.png">
> > **4. The underline under the footer links doesn't seem to be offset as much as the other links** Now (as seen in this PR): <img alt="Screenshot 2023-03-27 at 12 30 41" width="109" src="https://user-images.githubusercontent.com/113986285/227929686-6506ca9d-c411-4ebd-8e9f-d34c3a092c0b.png">
> > Previously (as seen in `develop`): <img alt="Screenshot 2023-03-27 at 12 30 48" width="108" src="https://user-images.githubusercontent.com/113986285/227929689-923bb7f3-228f-4dde-8d5b-132980538f4d.png">
> > **5. The icons are now being underlined** <img alt="Screenshot 2023-03-27 at 12 31 25" width="82" src="https://user-images.githubusercontent.com/113986285/227929692-049f2f7d-1890-47ea-94a2-bf538b83542a.png">
> 
> Now that we discovered that text-decoration-thickness and text-underline-offset aren't having any effect in safari, there seems to be no other way to restrict the underline to just the text within a link, so it's underlining the icons and extending the line on the ellipsis etc. So I'm not too sure of a fix for these issues, it may be worth a bigger team discussion about whether we just wait for percentage values for text-decoration-thickness and text-underline-offset to be compatible with safari as it seems to work for most other browsers.

I haven't looked into the issue in the detail you have here. But I think I agree with implementing the best fix for now and adding another ticket to look into the Safari fix, dependent on their future support of what you mentioned. It'd just be worth checking in with design with your decision.

2023-03-27 12:39 UTC, MI6-255 commented
> > Hey, just had another look at the build and found a few bugs: **1. The icons is also being underlined for the breadcrumbs component** <img alt="Screenshot 2023-03-27 at 12 26 08" width="174" src="https://user-images.githubusercontent.com/113986285/227929672-75afe3ac-0b70-4a3b-b538-0e552467e9b2.png"> <img alt="Screenshot 2023-03-27 at 12 26 17" width="160" src="https://user-images.githubusercontent.com/113986285/227929674-0659fc90-c10d-4182-81db-94b52e626cce.png">
> > **2. Small issue but the underline under the ellipsis (...) extends past the ellipsis, which it didn't before** <img alt="Screenshot 2023-03-27 at 12 26 47" width="49" src="https://user-images.githubusercontent.com/113986285/227929677-0b4b644d-10f4-4318-a19e-a71cec9eae56.png">
> > **3. The thickness of the underline in the cards looks slightly off** Now (as seen in this PR): <img alt="Screenshot 2023-03-27 at 12 28 01" width="534" src="https://user-images.githubusercontent.com/113986285/227929679-3fc114de-8332-4f14-8ff8-eed7d56a919c.png">
> > Previously (as seen in `develop`): <img alt="Screenshot 2023-03-27 at 12 28 07" width="533" src="https://user-images.githubusercontent.com/113986285/227929684-2a66f5d1-e06d-45e9-b071-c8191c751f5f.png">
> > **4. The underline under the footer links doesn't seem to be offset as much as the other links** Now (as seen in this PR): <img alt="Screenshot 2023-03-27 at 12 30 41" width="109" src="https://user-images.githubusercontent.com/113986285/227929686-6506ca9d-c411-4ebd-8e9f-d34c3a092c0b.png">
> > Previously (as seen in `develop`): <img alt="Screenshot 2023-03-27 at 12 30 48" width="108" src="https://user-images.githubusercontent.com/113986285/227929689-923bb7f3-228f-4dde-8d5b-132980538f4d.png">
> > **5. The icons are now being underlined** <img alt="Screenshot 2023-03-27 at 12 31 25" width="82" src="https://user-images.githubusercontent.com/113986285/227929692-049f2f7d-1890-47ea-94a2-bf538b83542a.png">
> 
> Now that we discovered that text-decoration-thickness and text-underline-offset aren't having any effect in safari, there seems to be no other way to restrict the underline to just the text within a link, so it's underlining the icons and extending the line on the ellipsis etc. So I'm not too sure of a fix for these issues, it may be worth a bigger team discussion about whether we just wait for percentage values for text-decoration-thickness and text-underline-offset to be compatible with safari as it seems to work for most other browsers.

I haven't looked into the issue in the detail you have here. But I think I agree with implementing the best fix for now and adding another ticket to look into the Safari fix, dependent on their future support of what you mentioned. It'd just be worth checking in with design with your decision.

2023-03-27 12:39 UTC, MI6-255 commented
> > Hey, just had another look at the build and found a few bugs: **1. The icons is also being underlined for the breadcrumbs component** <img alt="Screenshot 2023-03-27 at 12 26 08" width="174" src="https://user-images.githubusercontent.com/113986285/227929672-75afe3ac-0b70-4a3b-b538-0e552467e9b2.png"> <img alt="Screenshot 2023-03-27 at 12 26 17" width="160" src="https://user-images.githubusercontent.com/113986285/227929674-0659fc90-c10d-4182-81db-94b52e626cce.png">
> > **2. Small issue but the underline under the ellipsis (...) extends past the ellipsis, which it didn't before** <img alt="Screenshot 2023-03-27 at 12 26 47" width="49" src="https://user-images.githubusercontent.com/113986285/227929677-0b4b644d-10f4-4318-a19e-a71cec9eae56.png">
> > **3. The thickness of the underline in the cards looks slightly off** Now (as seen in this PR): <img alt="Screenshot 2023-03-27 at 12 28 01" width="534" src="https://user-images.githubusercontent.com/113986285/227929679-3fc114de-8332-4f14-8ff8-eed7d56a919c.png">
> > Previously (as seen in `develop`): <img alt="Screenshot 2023-03-27 at 12 28 07" width="533" src="https://user-images.githubusercontent.com/113986285/227929684-2a66f5d1-e06d-45e9-b071-c8191c751f5f.png">
> > **4. The underline under the footer links doesn't seem to be offset as much as the other links** Now (as seen in this PR): <img alt="Screenshot 2023-03-27 at 12 30 41" width="109" src="https://user-images.githubusercontent.com/113986285/227929686-6506ca9d-c411-4ebd-8e9f-d34c3a092c0b.png">
> > Previously (as seen in `develop`): <img alt="Screenshot 2023-03-27 at 12 30 48" width="108" src="https://user-images.githubusercontent.com/113986285/227929689-923bb7f3-228f-4dde-8d5b-132980538f4d.png">
> > **5. The icons are now being underlined** <img alt="Screenshot 2023-03-27 at 12 31 25" width="82" src="https://user-images.githubusercontent.com/113986285/227929692-049f2f7d-1890-47ea-94a2-bf538b83542a.png">
> 
> Now that we discovered that text-decoration-thickness and text-underline-offset aren't having any effect in safari, there seems to be no other way to restrict the underline to just the text within a link, so it's underlining the icons and extending the line on the ellipsis etc. So I'm not too sure of a fix for these issues, it may be worth a bigger team discussion about whether we just wait for percentage values for text-decoration-thickness and text-underline-offset to be compatible with safari as it seems to work for most other browsers.

I haven't looked into the issue in the detail you have here. But I think I agree with implementing the best fix for now and adding another ticket to look into the Safari fix, dependent on their future support of what you mentioned. It'd just be worth checking in with design with your decision.

2023-03-27 12:40 UTC, MI6-255 commented
> > Hey, just had another look at the build and found a few bugs: **1. The icons is also being underlined for the breadcrumbs component** <img alt="Screenshot 2023-03-27 at 12 26 08" width="174" src="https://user-images.githubusercontent.com/113986285/227929672-75afe3ac-0b70-4a3b-b538-0e552467e9b2.png"> <img alt="Screenshot 2023-03-27 at 12 26 17" width="160" src="https://user-images.githubusercontent.com/113986285/227929674-0659fc90-c10d-4182-81db-94b52e626cce.png">
> > **2. Small issue but the underline under the ellipsis (...) extends past the ellipsis, which it didn't before** <img alt="Screenshot 2023-03-27 at 12 26 47" width="49" src="https://user-images.githubusercontent.com/113986285/227929677-0b4b644d-10f4-4318-a19e-a71cec9eae56.png">
> > **3. The thickness of the underline in the cards looks slightly off** Now (as seen in this PR): <img alt="Screenshot 2023-03-27 at 12 28 01" width="534" src="https://user-images.githubusercontent.com/113986285/227929679-3fc114de-8332-4f14-8ff8-eed7d56a919c.png">
> > Previously (as seen in `develop`): <img alt="Screenshot 2023-03-27 at 12 28 07" width="533" src="https://user-images.githubusercontent.com/113986285/227929684-2a66f5d1-e06d-45e9-b071-c8191c751f5f.png">
> > **4. The underline under the footer links doesn't seem to be offset as much as the other links** Now (as seen in this PR): <img alt="Screenshot 2023-03-27 at 12 30 41" width="109" src="https://user-images.githubusercontent.com/113986285/227929686-6506ca9d-c411-4ebd-8e9f-d34c3a092c0b.png">
> > Previously (as seen in `develop`): <img alt="Screenshot 2023-03-27 at 12 30 48" width="108" src="https://user-images.githubusercontent.com/113986285/227929689-923bb7f3-228f-4dde-8d5b-132980538f4d.png">
> > **5. The icons are now being underlined** <img alt="Screenshot 2023-03-27 at 12 31 25" width="82" src="https://user-images.githubusercontent.com/113986285/227929692-049f2f7d-1890-47ea-94a2-bf538b83542a.png">
> 
> Now that we discovered that text-decoration-thickness and text-underline-offset aren't having any effect in safari, there seems to be no other way to restrict the underline to just the text within a link, so it's underlining the icons and extending the line on the ellipsis etc. So I'm not too sure of a fix for these issues, it may be worth a bigger team discussion about whether we just wait for percentage values for text-decoration-thickness and text-underline-offset to be compatible with safari as it seems to work for most other browsers.

I haven't looked into the issue in the detail you have here. But I think I agree with implementing the best fix for now and adding another ticket to look into the Safari fix, dependent on their future support of what you mentioned. It'd just be worth checking in with design with your decision.

2023-04-04 08:27 UTC, GCHQ-Developer-112 approved these changes

2023-04-05 16:07 UTC, jd239 approved these changes

2023-04-06 15:13 UTC, merged