268 search select loading states
mi6/ic-ui-kit pull request #517
Opened 2023-03-27 15:22 UTC by GCHQ-Developer-741

## Summary of the changes
Implemented loading states for select and search bar when using external filtering

## Related issue
#268 

## Checklist
- [x] I have added relevant unit and visual regression tests.
- [x] I have manually accessibility tested any changes, if relevant.
- [x] I have ensured any changes match the Figma component library.

2023-03-28 08:48 UTC, GCHQ-Developer-741 commented
Since the deployment links didn't get added...

Web Components: https://mi6.github.io/ic-ui-kit/branches/268-search-select-loading-states/web-components/
React: https://mi6.github.io/ic-ui-kit/branches/268-search-select-loading-states/react/

2023-03-29 14:42 UTC, ad9242 requested changes

2023-03-29 14:42 UTC, ad9242 commented on audit-ci.json
> +    "GHSA-hc6q-2mpp-qw7j"
think a rebase will remove need for this

2023-03-29 14:45 UTC, ad9242 commented
Found a bit of a strange one:

- type a value in so that loading displays (and then loading error)

![image](https://user-images.githubusercontent.com/116102637/228575931-d881d168-9875-41a5-af80-71cd56e970e3.png)

- tab focus to retry button (a bit strange that focus border is chopped off):
![image](https://user-images.githubusercontent.com/116102637/228576240-992415b0-9843-4c84-8710-22a06112205d.png)

- now use ArrowUp or ArrowDown: the loading error gets the focussed option styling:
![image](https://user-images.githubusercontent.com/116102637/228576466-bac149e3-cb12-4cef-a959-3530e3eba507.png)

2023-03-30 14:44 UTC, jd239 commented
Can the commits be fixed please. There are updates in different packages but only a single web-component commit.

2023-03-30 15:38 UTC, jd239 commented
2 issues when using the loading stats

1.
- Type in two letters
- Trigger the loading error
- Tab to retry button and press enter
- Menu disappears
Should that keep the menu open and show loading again?

2.
- Type in two letters
- Trigger the loading error
- Tab to retry button and press space
- Loading error has focus with the action blue so initially couldn't tell that the retry button was still there.

2023-03-30 15:38 UTC, jd239 requested changes
Added a few comments. More to do with coding standards rather than implementation. Good work. Looks slick!

2023-03-30 15:38 UTC, jd239 commented on packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
> +  @Prop() timeout?: number = null;
Think we need to add `null` as a data type here as it's not just number.

2023-03-30 15:38 UTC, jd239 commented on packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
> +const LOADING_ERROR_LABEL = "Loading Error";
Should these two be a prop so they can be changed but have the default as they are above.

2023-03-30 15:46 UTC, GCHQ-Developer-741 commented on packages/web-components/src/components/ic-menu/ic-menu.tsx
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
The actual Menu class. It never gets actually referenced so all the components have a warning which isn't really relevant. Thought to add this to get rid of the warning

2023-03-30 19:10 UTC, jd239 commented
Just had a thought. Is it possible to use the loading state with internal filtering?
- RE: Search bar. When typing the initial search phrase, the request is made to the back end to retrieve all the options (loading state appears) and then the internal filtering is used to filter the options
- RE: Select/Searchable. User clicks on the input/select to open the menu and then makes a request (loading state appears). Searchable will then use the internal filter.

2023-04-11 15:51 UTC, MI6-451 approved these changes

2023-04-13 12:48 UTC, jd239 commented
> Just had a thought. Is it possible to use the loading state with internal filtering?
> 
> * RE: Search bar. When typing the initial search phrase, the request is made to the back end to retrieve all the options (loading state appears) and then the internal filtering is used to filter the options
> * RE: Select/Searchable. User clicks on the input/select to open the menu and then makes a request (loading state appears). Searchable will then use the internal filter.

Has this been implemented as well? If so, is there a story to test this?

2023-04-21 09:09 UTC, ad9242 commented
Space is working now - thanks! Just a couple of things spotted:

1) when using searchable select eg searchable default story (https://mi6.github.io/ic-ui-kit/branches/268-search-select-loading-states/web-components/?path=/story/web-components-select--searchable-default), the select loses the focus border as you type eg
- click in field: focus is correct with drop down displayed:
![image](https://user-images.githubusercontent.com/116102637/233595542-a3e9d9f3-c0ed-4b5d-b9e9-080413e987be.png)


- now type "ca" - it loses focus border (but displays correct filtered options)
![image](https://user-images.githubusercontent.com/116102637/233595750-fa614350-aef3-4d23-bdb9-0e9127a24751.png)

this is the behaviour on develop branch (different options though)
![image](https://user-images.githubusercontent.com/116102637/233595844-91ef513d-0a27-49f2-a36b-564ccb8b66e9.png)

2) the "x" clear button disappears when in the loading error state:
![image](https://user-images.githubusercontent.com/116102637/233596052-bc6de53a-8258-4409-8649-1a23127a0935.png)

2023-04-24 15:31 UTC, ad9242 commented
sorry, a couple more issues:

1) type "es" & get the loading error\retry:
![image](https://user-images.githubusercontent.com/116102637/234043970-008c3382-aeac-44b1-af3e-c3292c7b96b2.png)
- now clear the clear selection "x"
- type in the field & you no longer get any suggestions

2) type into the field so that loading error\retry appears
- use keyboard to select "retry"
- options are updated, but the input has lost focus so you cannot select anything with arrow keys

2023-05-04 14:33 UTC, ad9242 approved these changes

2023-05-05 08:02 UTC, MI6-451 approved these changes

2023-05-05 10:25 UTC, ad9242 approved these changes

2023-05-05 11:02 UTC, MI6-451 approved these changes

2023-05-09 10:50 UTC, jd239 approved these changes

2023-05-09 10:52 UTC, merged