Pagination 1
mi6/ic-ui-kit pull request #555
Opened 2023-04-05 15:10 UTC by gd2910

## Summary of the changes
Adds ic-pagination and ic-pagination-item components

## Related issue
#481 

## Checklist
- [ ] I have added relevant unit and visual regression tests.
- [ ] I have manually accessibility tested any changes, if relevant.
- [ ] I have ensured any changes match the Figma component library.

2023-04-05 15:23 UTC, MI6-451 approved these changes

2023-04-11 13:03 UTC, GCHQ-Developer-847 requested changes
Just two more tiny things - otherwise looks great :)

2023-04-11 14:03 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-pagination-item/ic-pagination-item.css
> +  margin: 4px var(--ic-space-xxxs);
Can this 4px be updated to a token?

2023-04-11 14:05 UTC, GCHQ-Developer-530 commented on packages/react/src/stories/ic-pagination.stories.mdx
> +      <p style={{ padding: 10 }}>Adacent: 0, Boundary: 0</p>
```suggestion
      <p style={{ padding: 10 }}>Adjacent: 0, Boundary: 0</p>
```
I think this line has been copy and pasted for the rest so will need updating for those too

2023-04-18 09:06 UTC, GCHQ-Developer-847 commented
> High-contrast mode doesn't display the selected page

Looks like this is still an issue (everything else looks good to me though)

2023-04-18 12:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=555) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=555) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: gd2910<br/>:x: github-actions[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=555) it.</sub>

2023-04-18 13:16 UTC, GCHQ-Developer-847 approved these changes

2023-04-18 16:11 UTC, merged