Popover fixes
mi6/ic-ui-kit pull request #562
Opened 2023-04-11 08:25 UTC by GCHQ-Developer-530

## Summary of the changes
Update popover to display none instead of opacity 0.

## Checklist
- [x] I have added relevant unit and visual regression tests.
- [x] I have manually accessibility tested any changes, if relevant.
- [x] I have ensured any changes match the Figma component library.

2023-04-11 14:01 UTC, GCHQ-Developer-741 submitted a review, later dismissed

2023-04-12 09:16 UTC, jd239 requested changes
Two minor comments

2023-04-12 09:16 UTC, jd239 commented on packages/web-components/src/components/ic-popover-menu/ic-popover-menu.css
> +    transition: display var(--ic-transition-duration-fast);
Is there any animation on `display block`? If the transition property is removed, what happens?

2023-04-12 11:06 UTC, GCHQ-Developer-112 approved these changes

2023-04-12 11:54 UTC, GCHQ-Developer-112 approved these changes

2023-04-12 12:14 UTC, jd239 approved these changes

2023-04-12 12:15 UTC, merged