fix(web-components): added functionality to link tabs when added/removed prog…
mi6/ic-ui-kit pull request #574
Opened 2023-04-13 14:19 UTC by GCHQ-Developer-741

…ramatically

tabs will now work even when updated programatically and new ones are added to the context after initial render

Edit: PR has been updated to include tabs which have been removed dynamically. 

## Related issue
#568

2023-04-13 15:59 UTC, jd239 requested changes
Should we do something if a tab gets removed as well?

2023-04-13 15:59 UTC, jd239 commented on packages/web-components/src/components/ic-tab/ic-tab.tsx
> +  @Event() tabCreated: EventEmitter<HTMLIcTabElement>;
Internal?

2023-04-18 08:53 UTC, jd239 reviewed
I made updates to the ticket so don't think I'm best to review after doing the first round of reviews.

2023-04-18 09:10 UTC, GCHQ-Developer-530 approved these changes

2023-04-18 09:21 UTC, GCHQ-Developer-847 approved these changes

2023-04-18 10:04 UTC, merged