fix(web-components): added margin left to mobile app container
mi6/ic-ui-kit pull request #576
Opened 2023-04-14 11:31 UTC by za2201

## Summary of the changes
added margin left to app title container on mobile to fit focus state

## Related issue
#540 

## Checklist
- [x] I have added relevant unit and visual regression tests.
- [] I have manually accessibility tested any changes, if relevant.
- [] I have ensured any changes match the Figma component library.

2023-04-14 14:27 UTC, GCHQ-Developer-112 requested changes
This fix affects the design of the extra small top nav. Please could you try another fix that doesn't affect the padding/margins in the top nav

2023-04-14 14:27 UTC, GCHQ-Developer-112 commented on packages/web-components/src/components/ic-top-navigation/ic-top-navigation.css
> +    margin-left: var(--ic-space-xs);
The app details container was designed to be positioned 8px from the left in mobiles. This change will mean that the extra small top navigation will not look as the designers intend

2023-04-14 15:19 UTC, GCHQ-Developer-112 commented on packages/web-components/src/components/ic-top-navigation/ic-top-navigation.css
> +    margin-left: var(--ic-space-xs);
Please ignore the comment above. I've spoken to the design team who are happy with pushing the app title to the right 4px

2023-04-14 15:20 UTC, jd239 commented
Slight update for this ticket. We have noticed a negative margin-left which should be removed instead of the additional styling added as part of the ticket: https://github.com/mi6/ic-ui-kit/blob/develop/packages/web-components/src/components/ic-top-navigation/ic-top-navigation.css#L24

2023-04-17 10:44 UTC, GCHQ-Developer-112 submitted a review, later dismissed

2023-04-17 16:22 UTC, jd239 approved these changes

2023-04-18 09:42 UTC, GCHQ-Developer-847 approved these changes

2023-04-18 12:47 UTC, GCHQ-Developer-112 approved these changes

2023-04-18 12:47 UTC, merged