Pagination bar
mi6/ic-ui-kit pull request #614
Opened 2023-04-25 10:17 UTC by MI6-451

## Summary of the changes
Adds the pagination bar component which houses a pagination component with additional controls and information displayed. Some aspects of the design have not yet been implemented, associated tickets/issues are linked below. 

## Related issue
Component ticket/issue: #460 
Blocked by: #611, #612, #613, 

## Checklist
- [x] I have added relevant unit and visual regression tests.
- [x] I have manually accessibility tested any changes, if relevant.
- [x] I have ensured any changes match the Figma component library.

2023-05-11 21:19 UTC, jd239 commented
Is it worth closing this now and then reopening when all the blockers have been completed?

2023-06-09 12:42 UTC, GCHQ-Developer-847 requested changes
Looks great :) only a few small comments from me

2023-06-09 12:42 UTC, GCHQ-Developer-847 commented on packages/web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx
The 'go to page' input shows the error validation state when you first tab to it and says 'Please enter a number'

2023-06-12 06:42 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx
This also happens if you input a number and press enter

2023-06-13 10:27 UTC, MI6-451 commented on packages/web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx
Should both be sorted now

2023-06-13 13:31 UTC, merged