Develop > Main
mi6/ic-ui-kit pull request #645
Opened 2023-05-02 12:36 UTC by ad9242

## Summary of the changes
Beta.12 release of components.

## Related issue
N/A

## Checklist
- [ ] I have added relevant unit and visual regression tests.
- [ ] I have manually accessibility tested any changes, if relevant.
- [ ] I have ensured any changes match the Figma component library.

2023-05-02 12:47 UTC, GCHQ-Developer-112 submitted a review, later dismissed

2023-05-02 13:06 UTC, jd239 approved these changes

2023-05-02 13:09 UTC, jd239 requested changes
Should this be in the release? https://github.com/mi6/ic-ui-kit/pull/647/files

2023-05-03 08:28 UTC, jd239 approved these changes

2023-05-03 08:30 UTC, GCHQ-Developer-112 approved these changes

2023-05-03 08:40 UTC, merged