fix(web-components): fixed focus behaviour on blurring of menu for ic…
mi6/ic-ui-kit pull request #695
Opened 2023-05-17 10:52 UTC by GCHQ-Developer-741

…-select

changed focus behaviour to focus ic-select onKeyPress when the ic-menu is focused, as well as writing a test for code coverage

## Related issue
#455

2023-05-18 08:30 UTC, GCHQ-Developer-530 submitted a review, later dismissed

2023-05-18 10:41 UTC, jd239 requested changes
Looks good. I wonder if this behaviour should be added to search bar as well. I appreciate this may open a can of worms though.

2023-05-18 10:41 UTC, jd239 commented on packages/web-components/src/components/ic-select/ic-select.spec.tsx
> +  it("should focus the input when escape is pressed whilst the menu is focused", async () => {
Is there a test for searchable as well?

2023-05-18 16:43 UTC, GCHQ-Developer-741 commented
> Looks good. I wonder if this behaviour should be added to search bar as well. I appreciate this may open a can of worms though.

It certainly does. For searchbar this behaviour already works when Enter is pressed as this selects an option which focuses back to the parentEl. However, a similar approach for Escape causes the menu to open again before closing (flickering) which causes an e2e test to fail. I believe its because ic-search-bar opens the menu when it is focused. If its deemed to be necessary then I can investigate further otherwise could just raise a low priority ticket.

2023-05-19 13:23 UTC, GCHQ-Developer-530 approved these changes

2023-05-19 13:26 UTC, merged