docs(web-components): update prop and event descriptions for select to be less ambiguous
mi6/ic-ui-kit pull request #701
Opened 2023-05-19 09:32 UTC by GCHQ-Developer-530

## Summary of the changes
Update prop and event descriptions for select to be less ambiguous. Updated boolean props to follow "If true" pattern. Also specified any events that are specific to searchable variant.

## Related issue
#664

## Checklist
- [x] I have added relevant unit and visual regression tests.
- [x] I have manually accessibility tested any changes, if relevant.
- [x] I have ensured any changes match the Figma component library.

2023-05-22 14:50 UTC, jd239 commented on packages/web-components/src/components/ic-select/ic-select.tsx
> +   * The value of the select, reflected by the value of the currently selected option.
I'm not sure if this covers all bases because a searchable value may not come a selected option.

2023-05-22 14:51 UTC, jd239 requested changes
Just a single comment. :)

2023-05-22 17:22 UTC, GCHQ-Developer-112 approved these changes

2023-05-23 07:58 UTC, jd239 approved these changes

2023-05-23 07:59 UTC, merged