Date Input
mi6/ic-ui-kit pull request #797
Opened 2023-06-18 22:17 UTC by jd239

## Summary of the changes
Date Input componet. 
Includes:
- Unit, E2E, Visual Regression and a11y automated
- Web component and react stories

## Related issue
#334 

## Checklist
- [x] I have added relevant unit and visual regression tests.
- [x] I have manually accessibility tested any changes, if relevant.
- [ ] I have ensured any changes match the Figma component library.

2023-06-19 12:41 UTC, GCHQ-Developer-530 commented
I found a bit of a weird bug where the date input focuses if you click anywhere alongside it. Other than that, it looks really good 😊

https://github.com/mi6/ic-ui-kit/assets/111882034/da7a8338-d03a-4959-8d15-e313bd4fddc6

2023-06-19 12:44 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-date-input/ic-date-input.css
> +}
Can these px values be converted to rem or variables?

2023-06-19 15:47 UTC, GCHQ-Developer-847 requested changes
Noticed a few things, but looking great overall!

Love the screen reader functionality in particular when using arrow keys to change the values - looks really good to me 👏

2023-06-19 15:47 UTC, GCHQ-Developer-847 commented on packages/web-components/src/components/ic-date-input/ic-date-input.tsx
> +  @Prop() required: boolean = false;
A few of these props are missing the question mark to show that they're optional

2023-06-21 15:53 UTC, jd239 commented on packages/web-components/src/components/ic-date-input/ic-date-input.tsx
> +  private setInputPreventBasedOnSelection = (input: HTMLInputElement) => {
In FF, if I add a value to day, (cursor moves to month), click back on day and then try and change the value, nothing happens. PreventInput was still set to true so this function is to check that the value matches the relevant day/month/year state and then set preventInput to false so the value can be updated. 

However, after you have said I've broken preventInput, fixing that might mean this is no longer required.

2023-06-22 09:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=797) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=797) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: jd239<br/>:x: github-actions[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=797) it.</sub>

2023-06-23 00:05 UTC, jd239 commented on packages/web-components/src/components/ic-date-input/ic-date-input.tsx
> +    //TODO Does this need to consider a string which includes Zulu time?
Will create a separate ticket for this

2023-06-23 00:08 UTC, jd239 commented on packages/web-components/src/components/ic-date-input/ic-date-input.tsx
> +  private setInputPreventBasedOnSelection = (input: HTMLInputElement) => {
After further investigation, `window.getSelection.toString` does not work in FF. This method was created to as a work around which will work in both but another session of Googling provide a more reliable alternative (use selectionStart and selectionEnd). However, this involved changing the inputs from number to text. I have added regex to capture anything that is not number and swallow the keypress. All unit tests and e2e tests pass so think it's okay

2023-06-23 21:08 UTC, jd239 commented on packages/web-components/src/components/ic-date-input/ic-date-input.tsx
This has been fixed.

2023-06-28 08:36 UTC, gd2910 commented
Components should now follow the [Stencil style guide](https://stenciljs.com/docs/style-guide)

2023-06-29 13:58 UTC, jd239 commented
> Components should now follow the [Stencil style guide](https://stenciljs.com/docs/style-guide)

Done :)

2023-06-29 14:06 UTC, gd2910 commented on packages/web-components/src/components/ic-date-input/ic-date-input.tsx
> +  @Element() el: HTMLIcDateInputElement;
Element should be inbetween private variables and states :)

2023-06-29 14:15 UTC, gd2910 commented
In the story 'with value, after changing the value and logging, the mm/yy values change but not the dd value, possibly just a SB story nuance?

2023-06-30 11:59 UTC, GCHQ-Developer-741 commented
> I found a bit of a weird bug where the date input focuses if you click anywhere alongside it. Other than that, it looks really good blush
> 
>  Screen.Recording.2023-06-19.at.13.38.18.mov

Sorry if I've missed discussion of this issue, but I've noticed this on other components in our design system. One that caught me out was the ic-switch component which I accidentally triggered doing the same thing in the video.

2023-07-03 10:53 UTC, jd239 commented
> In the story 'with value, after changing the value and logging, the mm/yy values change but not the dd value, possibly just a SB story nuance?

It was a problem with the component not update the relevant states.

2023-07-03 11:16 UTC, jd239 commented
> 

Was initially going to set the :host to inline-flex to fix this but then thought this will need to be added to all form controls. The issue with that is, switching from block to inline could break a lot applications which do not have the input wrapped in a blocked div so left it out. 

Will create a ticket to review for the next major version.

2023-07-03 12:38 UTC, gd2910 submitted a review, later dismissed

2023-07-04 12:41 UTC, GCHQ-Developer-530 commented
I only seem to be able to paste a date into the input when I right click and select paste, it doesn't do anything when I use a keyboard shortcut. Is this meant to be the case or should I be able to use both methods?

2023-07-11 15:45 UTC, gd2910 approved these changes

2023-07-12 13:24 UTC, jd239 commented
Enhancement to paste functionality:
- Before it was possible to paste more than two characters into the day input. This has now been restricted to only two.
- It is now possible to paste individual 'numeric' values into the inputs. For example, it is now possible to copy and paste '12' into the month input.
- Validation has been set to prevent invalid values into relevant inputs for example, it is not possible to paste '13' into the month input. A validation message below will appear which says, 'Please paste a valid day/month'. This does not affect year as any number can be placed in there
- Moving to the next or previous input while the paste validation has appeared will remove the message.

2023-07-14 08:57 UTC, DBD324 commented
Couple of small potential improvements:
- The error message when attempting to paste an invalid value into a single filed is great. For example, pasting '13' into a month field. However, if I try to paste '123' in the field, then no message is displayed and the paste fails. It would be great to provide the same validation message and treat this as an invalid input in the same way. 
- When pasting a full date string '25/12/2017' we can use '/' and '-' as the separator keys. It would be great to also include the '.' symbol as a separtor allowing dates formatted '25.12.2017' to be pasted in the same way. 
- It would be great to allow the selection of the whole date when using the 'cmd+a' key press, and then allow the deletion of the whole date with one press of the delete key. 
- On the month element, should we allow a user to enter a letter corresponding to a month? For example, entering 'S' would result in an '09' entered into the month element. Entering 'J' would put the first month beginning with J - January - 01. Entering 'JU' would put the first month beginning with JU - June - 06. Entering JUL would then allow July - 07. 
- The allowable character entries for the above month text behaviour would be as follows:
-- JA
--F
---MAR
--AP
--MAY
--JUN
--JUL
--AU
--S
--O
--N
--D

2023-07-14 08:58 UTC, DBD324 requested changes
Have added comment with a few changes requested.

2023-07-14 10:18 UTC, jd239 commented
> Couple of small potential improvements:
> 
> * The error message when attempting to paste an invalid value into a single filed is great. For example, pasting '13' into a month field. However, if I try to paste '123' in the field, then no message is displayed and the paste fails. It would be great to provide the same validation message and treat this as an invalid input in the same way.
> * When pasting a full date string '25/12/2017' we can use '/' and '-' as the separator keys. It would be great to also include the '.' symbol as a separtor allowing dates formatted '25.12.2017' to be pasted in the same way.

These have been added.


> * It would be great to allow the selection of the whole date when using the 'cmd+a' key press, and then allow the deletion of the whole date with one press of the delete key.

Based on the three inputs which we use to generate the day/month/year, this does not seem possible as all three inputs would need to be focus and selected at the same time. 

> * On the month element, should we allow a user to enter a letter corresponding to a month? For example, entering 'S' would result in an '09' entered into the month element. Entering 'J' would put the first month beginning with J - January - 01. Entering 'JU' would put the first month beginning with JU - June - 06. Entering JUL would then allow July - 07.
> * The allowable character entries for the above month text behaviour would be as follows:
>   -- JA
>   --F
>   ---MAR
>   --AP
>   --MAY
>   --JUN
>   --JUL
>   --AU
>   --S
>   --O
>   --N
>   --D

This will be added to a new ticket rather than added to this one. The date input specifies 2 characters (which would be assumed as numbers instead of text) for the MM. Having the ability to type text in seems like a nice to have rather than a must have.

2023-07-17 11:26 UTC, GCHQ-Developer-530 approved these changes

2023-07-17 14:56 UTC, merged