fix(web-components): added prop to prevent auto highlighting first op…
mi6/ic-ui-kit pull request #899
Opened 2023-07-14 11:08 UTC by GCHQ-Developer-741

…tion

this prop gives people the ability to submit terms not included in the options list, since it won't automatically populate the field with the first option

## Summary of the changes
In order to allow users to submit their own custom search terms, the automatic highlighting of the first option needed to be removed, so that the field doesn't get populated on submission of search. However, there are a few scenarios where this functionality is needed, for example on our guidance site, which functions more as a quick navigation tool and therefore relies on having the options highlighted to avoid 404 errors.

To add flexibility, I have added a new prop called `disableAutoHighlighting`, which is `false` by default but users can set this if they want the search bar to function more traditionally. **This prop name isn't the best, so any suggestions for a name that better encapsulates its full purpose would be greatly appreciated**.

A new ticket has been raised in design (https://github.com/mi6/ic-ui-kit/issues/897) to add some visual changes to the search bar when this prop is enabled, to make clear the difference in behaviour when this prop is used.

## Related issue
#798 

## Checklist
- [x] I have added relevant unit and visual regression tests.
- [x] I have manually accessibility tested any changes, if relevant.
- [x] I have ensured any changes match the Figma component library.

2023-07-14 12:09 UTC, DBD324 requested changes
Think we need to review the terminology here. The issue isn't as simple as just disabling auto highlighting. It actually creates a totally different mode of search interaction. Think the work is sound, we just need to be really careful about the prop naming and the prop description as it changes the search mode drastically. 

Perhaps we could use something like:
- goToSearchResult: false

or conversely
-searchForInputTerm: true. 

I would like the team to think about wording this so that its impact and function is understandable.

2023-07-18 10:26 UTC, jd239 submitted a review, later dismissed
Nice work. I will approve as the code update is good. :)

2023-07-21 09:13 UTC, GCHQ-Developer-847 requested changes

2023-07-21 09:13 UTC, GCHQ-Developer-847 commented on packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
Tried adding the prop set to "query" on the "With Options" story - if I type something in and then start deleting the text I've typed in, the first option gets highlighted

2023-07-21 09:31 UTC, GCHQ-Developer-847 commented
Just noticed another thing actually - on the React "With options" story, I've tried setting searchMode to "query" and then added `onIcSubmitSearch={(ev) => console.log(ev.detail.value)}`. When I type something in the input box and press enter, nothing gets logged to the console. 

So when someone sets the search mode to "query", should it actually allow them to submit it i.e. should it emit onIcSubmitSearch with the value they've typed in when they press enter? That means they can either submit the value of one of their options, or the custom value they've typed in (a bit like how it works in the "Default" story - whatever you've typed in gets submitted)

2023-07-21 09:34 UTC, GCHQ-Developer-847 commented
> Just noticed another thing actually - on the React "With options" story, I've tried setting searchMode to "query" and then added `onIcSubmitSearch={(ev) => console.log(ev.detail.value)}`. When I type something in the input box and press enter, nothing gets logged to the console.
> 
> So when someone sets the search mode to "query", should it actually allow them to submit it i.e. should it emit onIcSubmitSearch with the value they've typed in when they press enter? That means they can either submit the value of one of their options, or the custom value they've typed in (a bit like how it works in the "Default" story - whatever you've typed in gets submitted)

^ Actually this does work - it does get submitted, but only when there options. E.g. on the "With options" story, I can submit "ca" or "am" for example, as that brings up options that match. But when I type in a random string which doesn't match any option (when it says "No results found"), I can't submit it

2023-08-01 09:59 UTC, GCHQ-Developer-847 approved these changes
Approved (we have spoken about my previous comment and I am happy that it is all working as it should - was possibly fixed by another change)

2023-08-01 10:03 UTC, DBD324 approved these changes
Terminology seems much more understandable now, thank you.

2023-08-01 10:04 UTC, merged