fix(web-components): adds z-index for sticky page header #653
mi6/ic-ui-kit pull request #909
Opened 2023-07-17 13:56 UTC by j212122

adds new z-index var for sticky page header so select box does not overla

## Related issue
[#653 ](https://github.com/orgs/mi6/projects/2/views/1?pane=issue&itemId=27454988)

## Checklist

2023-07-19 08:30 UTC, GCHQ-Developer-530 approved these changes

2023-07-19 09:16 UTC, ad9242 requested changes
I think also need to add the new variable in for the .sticky-desktop class on line 131. It didn't solve the issue currently testing on guidance site

2023-07-21 09:48 UTC, GCHQ-Developer-847 approved these changes

2023-07-21 12:17 UTC, MI6-255 approved these changes

2023-07-31 14:10 UTC, closed without merging