Feature/right click contextual open for ic popover menu
mi6/ic-ui-kit pull request #934
Opened 2023-07-21 16:58 UTC by c95560

## Summary of the changes
Adds an optional right-click contextual menu open to the ic-popover-menu. This potentially reduces the number of mouse actions a user needs to take, and could provide useful mouse x-y position information for events (e.g. right-click - open menu - add new component at mouse x-y position)

## Related issue
None known

## Checklist
- [?] New web component and react stories added to demonstrate feature. Not clear if unit tests needed. Visual style not changed.
- [y] I have manually accessibility tested any changes, if relevant. Verified existing behaviour not broken.
- [y] I have ensured any changes match the Figma component library.

2023-07-21 16:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=934) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-ui-kit?pullRequest=934) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-ui-kit?pullRequest=934) it.</sub>

2023-07-24 16:15 UTC, jd239 commented
Hi @c95560. Thank you for your contribution. Can you please refer to the [Contributing ](https://github.com/mi6/ic-ui-kit/blob/main/CONTRIBUTING.md) file and make updates to your files, rebase and commits were relevant.

2023-07-31 12:20 UTC, GCHQ-Developer-530 requested changes
A couple of console logs left in there that can now be removed

2023-08-10 06:45 UTC, GCHQ-Developer-530 requested changes
Couple more comments

2023-08-10 06:45 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
> +  @Prop() renderY: number = null;
This prop will need it's own description.

2023-08-10 06:45 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
> +  private clickEventEleRect: DOMRect = undefined;
Please can you follow our [style guide](https://github.com/mi6/ic-ui-kit/blob/main/CONTRIBUTING.md#style-guide) and move the new private variables and props into the correct place in the file and in alphabetical order?

2023-08-10 06:45 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
> +   *  State for popover render position
Think this prop description should be specific to renderX

2023-08-10 07:02 UTC, GCHQ-Developer-530 requested changes
Please could you also squash your commits into one's that follow [conventional commits](https://github.com/mi6/ic-ui-kit/blob/main/CONTRIBUTING.md#git-commit). You should have one for your update to react stories and another for the web-components work you've done.

2023-08-10 17:24 UTC, c95560 commented
@GCHQ-Developer-530

Noticed some issues resolving merge conflict - duplicated functions etc. 
Rebuilt branch enacting requested changes and retested.
- Fixed a console error bug related to bad anchor element DOM query.
- Added missing prop descriptions, e.g. for renderX
- Improved style by alphabetically ordering declarations of class props, functions etc
- recommitted code as a single commit via conventional commits plugin
- removed console debug messages that had been left in ic-popover-menu.tsx
- removed commented out debug code
- fixed style issues with npm run prittier:fix
- fixed (minor) merge conflicts with latest changes from main

2023-08-11 07:44 UTC, GCHQ-Developer-530 requested changes

2023-08-11 07:44 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
> +    //document.documentElement.style.backgroundColor = 'red';
```suggestion
```

2023-08-11 07:44 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
> +   * If true, the ic-popover-menu will open when a MouseEvent button press occurs.
```suggestion
   * If `true`, the ic-popover-menu will open when a MouseEvent button press occurs.
```

2023-08-11 07:44 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
> +   * 4 = mouse browser forward
Might be worth exporting these as an enum and setting the type to that as we only want to accept these numbers, not any number, and they're for the equivalent close prop

2023-08-11 07:44 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
> +   *  absolute screen Y co-ordinate for popover menu render position.
```suggestion
   *  Absolute screen Y co-ordinate for popover menu render position.
```

2023-08-11 07:44 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
> +   *  absolute screen X co-ordinate for popover menu render position.
```suggestion
   *  Absolute screen X co-ordinate for popover menu render position.
```

2023-08-11 07:52 UTC, GCHQ-Developer-530 commented
Thanks for updating to our conventional commit style, there's just a couple of updates to be made with the commits:
- Remove the merge commit
- Separate work out into one commit containing only the react work -  this should contain the react scope instead of ic-popover-menu something like feat(react) and then detail the work you have done
- The rest of the work can go under the web-components scope - feat(web-components) and then detail the work you've done

2023-08-11 12:58 UTC, c95560 commented
@GCHQ-Developer-530 

All prior outstanding issues should be resolved.

- Resolved additional outstanding issues with style / commented code / linting issues
- Added enum to denote allowed mouse click actions for ic-popover-menu options
- Removed merge commit
- Synced with develop branch instead of main
- Separated commits to web component and react file changes

2023-08-14 07:46 UTC, GCHQ-Developer-530 requested changes

2023-08-14 07:46 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
> +
I think this should be exported from an ic-popover-menu.types.ts file like we've done for other components (see ic-button for an example)

2023-08-17 06:39 UTC, GCHQ-Developer-530 commented
Sorry, it seems to be failing on prettier. Please could you run prettier:fix?

2023-08-18 14:57 UTC, c95560 commented
newest changes should rectify linting issues @GCHQ-Developer-530

2023-08-22 07:55 UTC, GCHQ-Developer-530 requested changes
This change seems to have caused a unit test to fail, and isn't reaching the 80% test coverage threshold. Would you be able to add some tests for the code you've written? 😊
Also noticed there's a lot of console warnings about render X and render Y about them being immutable.

2023-09-05 15:15 UTC, jd239 requested changes
Apologies for the late response. First and foremost, thanks for contributing this complex functionality to the popover menu. 🎉 
A few comments have been added. In addition, it's worth checking out the [Contribution file on git commits](https://github.com/mi6/ic-ui-kit/blob/main/CONTRIBUTING.md#git-commit) on how to format the commit messages so they pass the linting step during build.

2023-09-05 15:15 UTC, jd239 commented on packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
> +  @Prop() mouseEventCloseButtonPressVals: IcPopoverMenuClickEnum[] = [
Can this be changed to `mouseButtonClosePopover` so it's more readable

2023-09-26 10:45 UTC, c95560 commented
I'm very short on time right now so probably won't have time to tidy this up to required standard if significant work is required.

Will revisit eventually - but more than happy to hand this off to another dev if they want to get it merged before any significant conflicts creep in.

2023-09-26 14:44 UTC, GCHQ-Developer-465 commented
> I'm very short on time right now so probably won't have time to tidy this up to required standard if significant work is required.
> 
> Will revisit eventually - but more than happy to hand this off to another dev if they want to get it merged before any significant conflicts creep in.

Hey there! Thank you for your contribution :) 

We are happy to carry on with this and update the PR. 

Thank you again, your contribution is much appreciated. We look forward to seeing more contributions!

2023-10-02 10:15 UTC, jd239 commented
This work is continues in https://github.com/mi6/ic-ui-kit/tree/feature/popover-right-click-functionality. This PR will be closed and a new PR will be created with the peer review comments.

2023-10-02 10:15 UTC, closed without merging