fix(web-components): adds short title functionality and prevents truncation
mi6/ic-ui-kit pull request #958
Opened 2023-07-28 14:44 UTC by j212122

## Summary of the changes
Adds functionality too allow long app title to be shortened on smaller viewports. Prevents truncation or ellipses of longer nav-items

## Related issue
#854 

## Checklist
- [x] I have added relevant unit and visual regression tests.

2023-07-31 07:28 UTC, GCHQ-Developer-530 requested changes

2023-07-31 07:28 UTC, GCHQ-Developer-530 commented on packages/web-components/src/components/ic-search-bar/readme.md
> -
This needs to stay in, you can run npm run build and it should bring it back

2023-07-31 08:33 UTC, GCHQ-Developer-530 approved these changes

2023-07-31 08:58 UTC, GCHQ-Developer-465 approved these changes

2023-07-31 13:14 UTC, jd239 commented on packages/web-components/.loki/reference/chrome_iphone7_Web_Components_Side_navigation_Short_title.png
How comes the padding around the app name here is bigger than the long title?

2023-07-31 13:16 UTC, jd239 commented on packages/web-components/src/components/ic-side-navigation/test/basic/ic-side-navigation.e2e.ts
> +    it.only("should toggle to short title at small screen sizes", async () => {
```suggestion
    it("should toggle to short title at small screen sizes", async () => {
```

2023-07-31 13:16 UTC, jd239 commented on packages/web-components/src/components/ic-side-navigation/test/basic/ic-side-navigation.e2e.ts
> +
👍

2023-07-31 13:16 UTC, jd239 requested changes
One minor change and a comment..

2023-08-02 08:26 UTC, jd239 commented
Noticed 2 issues:

1. Now that the navigation item label wraps, when opening an collapsed side nav (on md, lg and above), and then closing, because the width is reduced, the label squashes before it is fully faded out. An option is to force the width of the label to not collapse as the side nav collapses or, instead of a fade animation, it just disappears instantly

2. On collapsed icons with labels, when opening and closing the side nav, 'different navigation' gets cut off because the height and overflow is not aware of the wrapped label. 
![Capture](https://github.com/mi6/ic-ui-kit/assets/116016939/91779dbe-1f0e-4899-be9e-278e7d61af0c)

2023-08-11 09:25 UTC, jd239 approved these changes

2023-08-11 10:32 UTC, GCHQ-Developer-530 approved these changes

2023-08-14 10:49 UTC, merged